---
title: "How we estimated the trends and the doubling time in MSF EpiSitrep on Covid-19 epidemic"
author: "Francesco Grandesso"
date: "20 August 2020"
output: rmdformats::html_clean
---


*For any clarification, please contact Francesco.GRANDESSO@epicentre.msf.org.*


## How we estimated the trends

Trends were estimated on the number of cases (or deaths) observed over a period of the last 12 days.

On the 12-day time-series we first carried a smoothing using a 3-day moving average. As a result, we obtained a 10-day smoothed values for which we run a linear regression of the values in the natural logarithm scale using the following formula:

> <center> **lm(ln(smoothed values) ~ 10 days)** </center>

The standard error of the model was used to calculate the confidence intervals.

Trends presented in the report were defined using the coefficients of the linear regression as follows:

- **Increasing trend:** an upward trend that was statistically significant; this means a positive coefficient and the confidence intervals do not include 0.
- **Declining trend:** a downward trend that was statistically significant; this means a negative coefficient and the confidence intervals do not include 0.
- **Stable trend:** an upward or downward trend that was not statistically significant; this means an either positive or negative coefficient, but the confidence intervals include 0.

To ensure reliable estimates we estimate the trend only if the cumulative number cases (or deaths) during the 12-day period was higher than 50.

We opted to model the slope on window of 12 days because it includes 3 generation time of 4 days.


## How we estimated the doubling time

The doubling time is defined as the time it takes for the reported number of cases (or the reported number of deaths) to double in value.

It is estimated in number of days (or fraction of day); the less the number of days, the higher the increase rate of the number of cases or deaths.

Over the course of the epidemic we changed the the type of data used for the estimation.



### Until week 32-2020 (week ending on 9 August 2020)

We first calculated the cumulative number of cases (or deaths) for each country. We then selected the last 12 days of the time-series of each country and modelled the slope of the natural logarithm of the cumulative cases (or cumulative deaths) using a linear regression.


> <center> **linear model = lm(ln(cumulative cases) ~ 12 days)** </center>

The standard error of linear regression model was used to calculate the confidence intervals.

The doubling time was finally calculated as the ratio of the natural logarithm of 2 over the coefficient of the slope estimated by the model.

> <center> **doubling time = ln(2) / coeff(linear model)** </center>

To ensure reliable estimates we calculated the doubling time only if the cumulative cases (or deaths) was higher than 50 at the first day of the 12 days window that was used in the model.



### From week 33-2020 (week ending on 16 August 2020)

We first calculated the cumulative number of cases (or deaths) for each country. We then selected the last 12 days of the time-series of each country and modelled the slope of the natural logarithm of the cases counts (or deaths counts) using a linear regression.


> <center> **linear model = lm(ln(cases counts) ~ 12 days)** </center>

The standard error of linear regression model was used to calculate the confidence intervals.

The doubling time was finally calculated as the ratio of the natural logarithm of 2 over the coefficient of the slope estimated by the model.

> <center> **doubling time = ln(2) / coeff(linear model)** </center>

To ensure reliable estimates we calculated the doubling time only if the cumulative cases (or deaths) was higher than 50 at the first day of the 12 days window that was used in the model.

The changes in the way we calculated the doubling time was due to the multiple epidemic waves that several countries are experiencing, so that the changes in the cumulative count do not represent the actual epidemic stage.
