---
title: "Covid-19 MSF data analysis - OC level"
description: |
  Blablabla 
author:
  - name: Francesco Grandesso
    url: mailto:francesco.GRANDESSO@epicentre.msf.org
    affiliation: Epicentre
    affiliation_url: https://epicentre.msf.org/
  - name: Paul Campbell
    url: mailto:paul.CAMPBELLepicentre.msf.org
    affiliation: Epicentre
    affiliation_url: https://epicentre.msf.org/
date: '`r Sys.Date()`'
output:
  distill::distill_article:
    toc: TRUE
    toc_depth: 1
editor_options:
  chunk_output_type: console
---



<!-- Setup environment and upload functions -->
```{r setup, warning = FALSE, message = FALSE, include = FALSE}

if (!exists('path.root')) {
  source(here::here('R', 'setup.r'), encoding = 'UTF-8')
}

source(file.path(path.R, 'utils_management.R'), encoding = 'UTF-8')
source(file.path(path.R, 'utils_get_data.R')  , encoding = 'UTF-8')
source(file.path(path.R, 'utils_vis.R')       , encoding = 'UTF-8')


# Set the left and right censoring for date of consultation. 
# The right-censoring create also the week value and the folders where to save the outputs
dates_and_week <- set_date_frame(create_folders = TRUE)

date_min_report <- dates_and_week[[1]]
date_max_report <- dates_and_week[[2]]
week_report     <- dates_and_week[[3]]


OC <- "OCP"


caption_graph <- glue('Analysis and graphic by Epicentre | Data source: MSF linelists as of {format(date_max_report, "%d %b %Y")}')


knitr::opts_chunk$set(cache = FALSE,
                      echo = FALSE,
                      tidy = TRUE,
                      collapse = TRUE,
                      dpi = 150,
                      fig.width = 8,
                      fig.height = 5,
                      fig.align = "center",
                      warning = FALSE,
                      message = FALSE,
                      encoding = "UTF-8")

```

<!-- Import and manage data -->
```{r get-data, include = FALSE}

## Import the list of countries
df_countries <- readRDS(file.path(path.local.data, 'df_countries.RDS'))
# No idea where that came from, I found an old file from august in the episitrep country deprecated repo, and copied it in data/local.


## Import MSF linelist --- --- --- 
path.sharepoint.data <- file.path(path.sharepoint, 'data', 'linelist', 'world')

dta_linelist <- get_msf_linelist(force = TRUE) %>% 
  clean_msf_dta() %>% 
  prepare_msf_dta(shorten_var_names = TRUE) %>% 
  rename(iso_a3 = country) %>% 
  left_join(df_countries %>% select(continent, region, iso_a3, country), by = 'iso_a3') %>% 
  mutate(
    country = as.factor(country), 
    continent = as.factor(continent)) %>% 
  filter(between(date_consultation, left = date_min_report, right = date_max_report) | is.na(date_consultation)) %>%  # Filter date limits using date of consultation
  filter(across(
    .cols = contains(OC),
    .fns  = ~isTRUE(.x)))


## Import aggregated data --- --- --- 
dta_weekly_aggregated <- get_msf_aggregated(force = TRUE)
dta_project_aggregated_dates <- get_msf_aggregated_dates(force = TRUE)

### Remove temporarily Quito that grouped the whole activity in a single week
dta_weekly_aggregated <- dta_weekly_aggregated %>% 
  filter(project != 'Quito-Fixed & mobile brigades')


### Expand the aggregated
dta_aggregated_expanded <- dta_weekly_aggregated %>% 
  filter(!project %in% c('Lesvos-Moria', 'Lesvos-Moria Ped')) %>% 
  select(-week) %>% 
  mutate(
    date = as.Date(date), 
    epi_week_consultation = make_epiweek_date(date) %>% as.Date(), 
    country = case_when(
      country == 'DRC' ~ 'Democratic Republic of the Congo', 
      country == "Côte d'Ivoire" ~ 'Côte d’Ivoire', 
      TRUE ~ country)) %>% 
  left_join(df_countries, by = 'country') %>% 
  pivot_longer(cols = c('confirmed', 'probable', 'suspected', 'non_cases', 'unknown'), names_to = 'covid_status') %>% 
  filter(!is.na(value)) %>% 
    mutate(obs = purrr::map(value, ~rep_len(1, .x))) %>%
    unnest(cols = c(obs)) %>%
    select(-c(value, obs)) %>% 
    mutate(
      covid_status = factor(covid_status, levels = c('confirmed', 'probable', 'suspected', 'non_cases', 'unknown'), labels = c('Confirmed', 'Probable', 'Suspected', 'Not a case', 'Unknown'))) %>% 
  rename('OC' = oc, 'site_name' = project) %>% 
  filter(between(date, left = date_min_report, right = date_max_report) | is.na(date)) %>% 
  filter(OC == OC)



# The dataset with linelist and the expanded aggregated data together
dta_linelist_with_aggregated <- dta_linelist %>% 
  select(continent, region, country, site_name, iso_a3, OC, epi_week_consultation, covid_status) %>% 
  add_row(dta_aggregated_expanded %>% 
            select(continent, region, country, site_name, iso_a3, OC, epi_week_consultation, covid_status) %>% 
            mutate(
              country = paste(country, '(*)'), 
              site_name = paste(site_name, '(*)')))


tbl_aggregated_expanded_with_dates <- dta_aggregated_expanded %>% 
  distinct(sheet, OC, country, site_name) %>% 
  full_join(dta_project_aggregated_dates, by = 'sheet') %>% 
    mutate(
    country = case_when(
      country == 'DRC' ~ 'Democratic Republic of the Congo', 
      country == "Côte d'Ivoire" ~ 'Côte d’Ivoire', 
      TRUE ~ country)) %>% 
  pivot_longer(
    cols = date_first:date_last, 
    names_to = "type_date", 
    values_to = "date_consultation") %>% 
  left_join(df_countries, by = 'country') %>% 
    mutate(
      country = paste(country, '(*)'),
      site_name = paste(site_name, '(*)'))
```


