################# PER PROJECT INTERSECTION  ################

# Generate tables and figures for projects on intersection data
# Just a run of what was in the OC level script but in intersection,
# to explore and prepare a draft for the JS.
# (hence tables and figures numbers that may appear random)

# Setup -----------------------------------------------
if (!exists('path.root')) {
  source(here::here('R', 'setup.r'), encoding = 'UTF-8')
}

# Set locale (so that months appear in english and not French)
if (Sys.getlocale(category = "LC_TIME") == "French_France.1252") {
  Sys.setlocale(category = "LC_TIME", locale = "C")
  Sys.setenv(LANG = "en_GB.UTF-8") 
}

# Upload helper functions
source(file.path(path.R, 'utils_management.R'), encoding = 'UTF-8')
source(file.path(path.R, 'utils_get_data.R')  , encoding = 'UTF-8')
source(file.path(path.R, 'utils_vis.R')       , encoding = 'UTF-8')


# Set the left and right censoring for date of consultation.
# The right-censoring create also the week value and the folders where to save outputs
dates_and_week <- set_date_frame(create_folders = TRUE)

date_min_report <- dates_and_week[[1]]
date_min_report <- as.Date("2020-01-22")
date_max_report <- dates_and_week[[2]]
week_report     <- dates_and_week[[3]]



### SETUP PATHS ###
# If week folder not created already by overall sitrep, create it.
path.local.msf.extra <- file.path(path.local.msf, "extra", "per_project")

if (!dir.exists(path.local.msf.extra)) {
  dir.create(path.local.msf.extra,   showWarnings = FALSE, recursive = TRUE)
}


# Get data --------------------------------------------


# Geo and population data
df_countries <- readRDS(file.path(path.local.data, 'df_countries.RDS'))

# Linelist data 
# I'll import the data generated by the episitrep_msf_level_analysyses 
# (run episitrep_msf_level first)
load(file.path(path.local.msf.data, 
               glue('episitrep_msf_level_analyses_{week_report}.RData')))



# Prepare data ----------------------------------------

# Data for per project analysis: only the confirmed, probable and suspects
dta_linelist_project <- dta_linelist %>%
  filter(ind_MSF_covid_status %in% c('Confirmed', 'Probable', 'Suspected')) %>%
  mutate(MSF_severity = ifelse(is.na(MSF_severity), 
                               "Non available", 
                               MSF_severity),
         MSF_severity = factor(MSF_severity,
                               levels = c("Mild", "Moderate", "Severe", 
                                          "Critical", "Non available")),
         country_project = paste(iso_a3, project, sep = "_") )


# Data about tests
dta_testing <- dta_linelist %>%
  select(country, project, epi_week_consultation, merge_admit, 
         ind_MSF_covid_status, ind_outcome_patcourse_status, 
         matches("test|lab|sample")) %>%
  rowwise %>%
  mutate(
    test_1_10 = ifelse(MSF_test_type   == "PCR", 1, 0),
    test_2_10 = ifelse(MSF_test_type_2 == "PCR", 1, 0),
    test_3_10 = ifelse(MSF_test_type_3 == "PCR", 1, 0),
    test_4_10 = ifelse(MSF_test_type_4 == "PCR", 1, 0),
    n_test_PCR = sum(test_1_10, test_2_10, test_3_10, test_4_10, na.rm = TRUE),
    merge_test_PCR = ifelse(n_test_PCR >= 1, "Yes", "No"),
    
    test_result_1 = ifelse(MSF_test_type   == "PCR" & MSF_test_results   == "Positive", 1, 0),
    test_result_2 = ifelse(MSF_test_type_2 == "PCR" & MSF_test_results_2 == "Positive", 1, 0),
    test_result_3 = ifelse(MSF_test_type_3 == "PCR" & outcome_lab_result == "Positive", 1, 0),
    test_result_4 = ifelse(MSF_test_type_4 == "PCR" & MSF_test_results_4 == "Positive", 1, 0),
    n_test_PCR_positive = sum(test_result_1, test_result_2,
                              test_result_3, test_result_4, na.rm = TRUE),
    merge_test_PCR_positive = ifelse(n_test_PCR_positive >= 1, "Yes", "No")
  )


# Analysis by project --------------------------------------

# Inclusion criteria: patients were included in the study if 
# COVID suspected or probable or confirmed case independently
# of level of care provided in the project.

## Testing -------------------------------------------------
tble19 <- dta_testing %>%
  group_by(country, project) %>%
  summarise(n_patient_PCR = sum(merge_test_PCR == "Yes", na.rm = TRUE),
            n_patient_PCR_positive = sum(merge_test_PCR_positive == "Yes", na.rm = TRUE),
            perct_patient_pos = ifelse(n_patient_PCR == 0,
                                       NA_integer_,
                                       n_patient_PCR_positive / n_patient_PCR),
            a_patient_positive = format_nbp(n_patient_PCR_positive, perct_patient_pos),
            
            n_test_PCR = sum(n_test_PCR, na.rm = TRUE),
            n_test_PCR_positive =sum(n_test_PCR_positive, na.rm = TRUE),
            perct_test_pos = ifelse(n_test_PCR == 0,
                                    NA_integer_,
                                    n_test_PCR_positive / n_test_PCR),
            a_test_positive = format_nbp(n_test_PCR_positive, perct_test_pos)
  ) %>%
  select(-c(n_patient_PCR_positive, perct_patient_pos,  n_test_PCR_positive, perct_test_pos))




gtble19 <- tble19 %>%
  gt() %>%
  cols_label(
    country = 'Country',
    project = 'Project',
    
    n_test_PCR      = 'Total',
    a_test_positive = "Positive",
    
    n_patient_PCR      = "Total",
    a_patient_positive = "Positive") %>%
  
  tab_spanner(
    label   = 'Number of tests',
    columns = contains("_test_")) %>%
  tab_spanner(
    label   = 'Number of patients',
    columns = contains('_patient_')) %>%
  
  fmt_missing(
    columns      = starts_with('n_'),
    missing_text = "0") %>%
  
  cols_align(
    align   = 'center',
    columns = everything()) %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight     = "bold",
    data_row.padding          = px(2),
    row_group.padding         = px(2),
    row.striping.include_table_body = TRUE)  %>%
  
  summary_rows(
    columns = starts_with("n_"),
    fns = list(Total = "sum"),
    decimals = 0)

gtble19 %>%
  tab_header(
    title = 'Number of tests and patient tested')

gtsave(gtble19,
       file.path(path.local.msf.extra, paste0('gtble19', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()






## Time symptom onset to presentations ---------------------

fig4 <- dta_linelist_project %>%
  mutate(delay_before_consultation = as.numeric(MSF_date_consultation - patcourse_dateonset)) %>%
  filter(between(delay_before_consultation, left = 0, right = 50)) %>%
  # select(country, project, merge_admit, MSF_severity, MSF_length_stay) %>%
  group_by(continent, country, project) %>%
  summarise(x = quantile(delay_before_consultation, c(0.25, 0.5, 0.75), na.rm = TRUE),
            q = c(0.25, 0.5, 0.75),
            n = n()) %>%
  pivot_wider(names_from = q,
              values_from =x,
              names_prefix = "q_") %>%
  mutate(project = paste(country, project, sep = " - ")) %>%
  
  ggplot(aes(x = fct_reorder(project, desc(q_0.5)),
             y = q_0.5,
             colour = continent)) +
  geom_point(aes(size = n),
             shape = 19) +
  geom_errorbar(aes(ymin = q_0.25,
                    ymax = q_0.75),
                width = 0) +
  coord_flip() +
  labs(x = "",
       y = "Median time",
       title = "Median time between symptom onset\nand presentation",
       subtitle = "Median and interquartile range") +
  ggthemes::scale_colour_tableau(name = "Continent", palette = "Red-Blue-Brown") +
  scale_size_continuous(name = "Number of\npresentations",
                        breaks = c(10, 100, 1000, 5000)) +
  theme_light() +
  theme(legend.position = 'right',
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())

ggsave(file.path(path.local.msf.extra, paste0('fig4', '_', week_report, '.png')),
       plot = fig4,
       width = 7,
       height = 9,
       scale = 1.1,
       dpi = 320)

# fig4



## Patient visits and hospitalisation ----------------------

### Summary ------------------------------------------------

tble1 <- dta_linelist_project %>%
  select(country, project, patcourse_admit, outcome_patcourse_admit, merge_admit) %>%
  group_by(country, project) %>%
  summarise(n_patients           = n(),
            
            n_admitted_admission = sum(patcourse_admit == "Yes", na.rm = TRUE),
            p_admitted_admission = n_admitted_admission / n_patients,
            
            n_admited_post       = sum(outcome_patcourse_admit == "Yes" &
                                         patcourse_admit != "Yes", na.rm = TRUE),
            p_admited_post       = n_admited_post / n_patients,
            
            n_admit_all          = sum(merge_admit == "Yes", na.rm = TRUE),
            p_admit_all          = n_admit_all / n_patients)


gtble1 <- tble1 %>%
  gt() %>%
  cols_label(
    country              = 'Country',
    project              = 'Project',
    n_patients           = 'Visits',
    n_admitted_admission = 'N',
    p_admitted_admission = "%",
    n_admited_post       = 'N',
    p_admited_post       = "%",
    n_admit_all          = 'N',
    p_admit_all          = "%") %>%
  
  tab_spanner(
    label = 'Hospitalised at presentation',
    columns = ends_with('_admitted_admission')) %>%
  
  tab_spanner(
    label = 'Hospitalised during course of disease',
    columns = ends_with('_admited_post')) %>%
  
  tab_spanner(
    label = 'Hospitalised (any time)',
    columns = ends_with('_admit_all')) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  fmt_number(
    columns = starts_with('p_'),
    decimals = 1,
    scale_by = 100) %>%
  
  # cols_align(
  #   align = 'right',
  #   columns = starts_with('n_')) %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)  %>%
  
  summary_rows(
    columns = vars(n_patients, n_admitted_admission, n_admited_post, n_admit_all),
    fns = list(Total = "sum"),
    decimals = 0)


gtsave(gtble1,
       file.path(path.local.msf.extra, paste0('gtble1', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble1 %>%
  tab_header(
    title = 'Patient visits and hospitalisation status at admission and over course of disease, by project')


### By MSF_severity ----------------------------------------

tble2 <- dta_linelist_project %>%
  select(country, project, merge_admit, 
         MSF_severity, MSF_length_stay) %>%
  group_by(country, project) %>%
  summarise(n_patients = n(),
            n_admis    = sum(merge_admit == "Yes", na.rm = TRUE),
            
            n_mild       = sum(MSF_severity == "Mild", na.rm = TRUE),
            n_mild_admis = sum(MSF_severity == "Mild" & merge_admit == "Yes"),
            p_mild_admis = n_mild_admis / n_mild,
            
            n_moderate       = sum(MSF_severity == "Moderate", na.rm = TRUE),
            n_moderate_admis = sum(MSF_severity == "Moderate" & merge_admit == "Yes", na.rm = TRUE),
            p_moderate_admis = n_moderate_admis / n_moderate,
            
            n_severe       = sum(MSF_severity == "Severe", na.rm = TRUE),
            n_severe_admis  = sum(MSF_severity == "Severe" & merge_admit == "Yes", na.rm = TRUE),
            p_severe_admis = n_severe_admis / n_severe,
            
            n_critical        = sum(MSF_severity == "Critical", na.rm = TRUE),
            n_critical_admis  = sum(MSF_severity == "Critical" & merge_admit == "Yes", na.rm = TRUE),
            p_critical_admis  = n_critical_admis / n_critical,
            
            n_na       = sum(is.na(MSF_severity)),
            p_na       = n_na / n_patients)


gtble2 <- tble2 %>%
  gt() %>%
  cols_label(
    country    = 'Country',
    project    = 'Project',
    n_patients = 'Visits',
    n_admis    = 'Admissions',
    
    n_mild       = 'N visits',
    n_mild_admis = 'N admissions',
    p_mild_admis = "% admitted",
    
    n_moderate       = 'N visits',
    n_moderate_admis = 'N admissions',
    p_moderate_admis = "% admitted",
    
    n_severe       = 'N visits',
    n_severe_admis = 'N admissions',
    p_severe_admis = "% admitted",
    
    n_critical       = 'N visits',
    n_critical_admis = 'N admissions',
    p_critical_admis = "% admitted",
    
    n_na = 'MSF_severity',
    p_na = "% non-available") %>%
  
  tab_spanner(
    label = 'All MSF_severity',
    columns = vars(n_patients, n_admis)) %>%
  tab_spanner(
    label = 'Mild',
    columns = contains('_mild')) %>%
  tab_spanner(
    label = 'Moderate',
    columns = contains('_moderate')) %>%
  tab_spanner(
    label = 'Severe',
    columns = contains('_severe')) %>%
  tab_spanner(
    label = 'Critical',
    columns = contains('_critical')) %>%
  tab_spanner(
    label = 'Missing data',
    columns = ends_with('_na')) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  fmt_number(
    columns = starts_with('p_'),
    decimals = 1,
    scale_by = 100) %>%
  
  cols_align(
    align = 'center') %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding  = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)

gtsave(gtble2,
       file.path(path.local.msf.extra, paste0('gtble2', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble2 %>%
  tab_header(
    title = 'Patient visits and hospitalisation by project and MSF_severity')


### Length of stay and MSF_severity ------------------------

tble3 <- dta_linelist_project %>%
  select(country, project, merge_admit, MSF_severity, MSF_length_stay) %>%
  group_by(country, project) %>%
  summarise(
    n_patients = n(),
    n_admis    = sum(merge_admit == "Yes", na.rm = TRUE),
    
    q_mild_25 = quantile(MSF_length_stay[merge_admit == "Yes" & MSF_severity == "Mild"], c(0.25), na.rm = TRUE),
    q_mild_50 = quantile(MSF_length_stay[merge_admit == "Yes" & MSF_severity == "Mild"], c(0.5), na.rm = TRUE),
    q_mild_75 = quantile(MSF_length_stay[merge_admit == "Yes" & MSF_severity == "Mild"], c(0.75), na.rm = TRUE),
    
    q_moderate_25 = quantile(MSF_length_stay[merge_admit == "Yes" & MSF_severity == "Moderate"], c(0.25), na.rm = TRUE),
    q_moderate_50 = quantile(MSF_length_stay[merge_admit == "Yes" & MSF_severity == "Moderate"], c(0.5), na.rm = TRUE),
    q_moderate_75 = quantile(MSF_length_stay[merge_admit == "Yes" & MSF_severity == "Moderate"], c(0.75), na.rm = TRUE),
    
    q_critical_25 = quantile(MSF_length_stay[merge_admit == "Yes" & MSF_severity == "Critical"], c(0.25), na.rm = TRUE),
    q_critical_50 = quantile(MSF_length_stay[merge_admit == "Yes" & MSF_severity == "Critical"], c(0.5), na.rm = TRUE),
    q_critical_75 = quantile(MSF_length_stay[merge_admit == "Yes" & MSF_severity == "Critical"], c(0.75), na.rm = TRUE),
    
    q_severe_25 = quantile(MSF_length_stay[merge_admit == "Yes" & MSF_severity == "Severe"], c(0.25), na.rm = TRUE),
    q_severe_50 = quantile(MSF_length_stay[merge_admit == "Yes" & MSF_severity == "Severe"], c(0.5), na.rm = TRUE),
    q_severe_75 = quantile(MSF_length_stay[merge_admit == "Yes" & MSF_severity == "Severe"], c(0.75), na.rm = TRUE),
    
    na_MSF_severity = sum(is.na(MSF_severity)),
    na_length_of_stay = sum(is.na(MSF_length_stay)),
    na_both = sum(is.na(MSF_severity) & is.na(MSF_length_stay))
  ) %>%
  
  mutate(iqr_mild     = glue("{q_mild_50} [{q_mild_25} - {q_mild_75}]"),
         iqr_moderate = glue("{q_moderate_50} [{q_moderate_25} - {q_moderate_75}]"),
         iqr_severe   = glue("{q_critical_50} [{q_critical_25} - {q_critical_75}]"),
         iqr_critical = glue("{q_severe_50} [{q_severe_25} - {q_severe_75}]")) %>%
  select(-starts_with("q_")) %>%
  relocate(country, project,
           starts_with("n_"),
           starts_with("iqr_"),
           starts_with("na_"))  %>%
  group_by(country)


gtble3 <- tble3 %>%
  gt() %>%
  cols_label(
    country    = 'Country',
    project    = 'Project',
    
    n_patients = 'Visits',
    n_admis    = 'Admissions',
    
    iqr_mild     = 'Mild',
    iqr_moderate = 'Moderate',
    iqr_severe   = 'Severe',
    iqr_critical = 'Critical',
    
    na_MSF_severity       = "MSF_severity",
    na_length_of_stay = "Length of stay",
    na_both           = "Both") %>%
  
  tab_spanner(
    label = 'Length  of Stay (Median [IQR])',
    columns = starts_with('iqr_')) %>%
  tab_spanner(
    label = 'Missing data',
    columns = starts_with('na')) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  cols_align(
    align = 'center') %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)  %>%
  
  summary_rows(
    columns = starts_with("n_"),
    fns = list(Total = "sum"),
    decimals = 0)


gtsave(gtble3,
       file.path(path.local.msf.extra, paste0('gtble3', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble3 %>%
  tab_header(
    title = 'Median length of stay according to MSF_severity')





## Age and gender ------------------------------------------

fig5 <- dta_linelist_project %>%
  drop_na(patinfo_sex) %>%
  mutate(Sex = factor(patinfo_sex,
                      levels = c('M', 'F'),
                      labels = c('Male', 'Female'))) %>%
  group_by(continent, country, project, Sex) %>%
  summarise(x = quantile(age_in_years, c(0.25, 0.5, 0.75), na.rm = TRUE),
            q = c(0.25, 0.5, 0.75),
            n = n()) %>%
  pivot_wider(names_from = q,
              values_from =x,
              names_prefix = "q_") %>%
  mutate(project = paste(country, project, sep = " - ")) %>%
  
  ggplot(aes(x = fct_reorder(project, desc(q_0.5)),
             y = q_0.5,
             colour = Sex,
             shape = Sex
  )) +
  geom_point(aes(size = n),
             position = position_dodge(width=0.9)) +
  geom_errorbar(aes(ymin = q_0.25,
                    ymax = q_0.75),
                width = 0,
                position = position_dodge(width=0.9)) +
  coord_flip() +
  labs(x = "",
       y = "Median age",
       title = "Median age (in years) of all presentations",
       subtitle = "Median and interquartile range") +
  
  scale_colour_manual(name = "Sex",
                      values = c("#4E79A7FF", "#A0CBE8FF"),
                      breaks = c("Male", "Female"),
                      labels = c("Male", "Female")) +
  
  scale_size_continuous(name = "Visits",
                        breaks = c(10, 100, 1000, 5000)) +
  
  theme_light() +
  theme(legend.position = 'right',
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())


ggsave(file.path(path.local.msf.extra, paste0('fig5', '_', week_report, '.png')),
       plot = fig5,
       width = 8,
       height = 14,
       scale = 1.1,
       dpi = 320)

# fig5



tble6 <- dta_linelist_project %>%
  select(country, project, ind_MSF_covid_status, merge_admit, Sex = patinfo_sex, age_in_years) %>%
  group_by(country, project, Sex) %>%
  summarise(
    n_patients = n(),
    n_admis    = sum(merge_admit == "Yes", na.rm = TRUE),
    
    n_probable_admis    = sum(ind_MSF_covid_status == "Probable" & merge_admit == "Yes", na.rm = TRUE),
    q_probable_25_admis = quantile(age_in_years[ind_MSF_covid_status == "Probable" & merge_admit == "Yes"], c(0.25), na.rm = TRUE),
    q_probable_05_admis = quantile(age_in_years[ind_MSF_covid_status == "Probable" & merge_admit == "Yes"], c(0.5), na.rm = TRUE),
    q_probable_75_admis = quantile(age_in_years[ind_MSF_covid_status == "Probable" & merge_admit == "Yes"], c(0.75), na.rm = TRUE),
    f_probable_admis    = format_med(q_probable_05_admis, q_probable_25_admis, q_probable_75_admis),
    
    n_confirmed_admis    = sum(ind_MSF_covid_status == "Confirmed" & merge_admit == "Yes", na.rm = TRUE),
    q_confirmed_25_admis = quantile(age_in_years[ind_MSF_covid_status == "Confirmed" & merge_admit == "Yes"], c(0.25), na.rm = TRUE),
    q_confirmed_05_admis = quantile(age_in_years[ind_MSF_covid_status == "Confirmed" & merge_admit == "Yes"], c(0.5), na.rm = TRUE),
    q_confirmed_75_admis = quantile(age_in_years[ind_MSF_covid_status == "Confirmed" & merge_admit == "Yes"], c(0.75), na.rm = TRUE),
    f_confirmed_admis = format_med(q_confirmed_05_admis, q_confirmed_25_admis, q_confirmed_75_admis),
    
    n_probable_out    = sum(ind_MSF_covid_status == "Probable" & merge_admit == "No", na.rm = TRUE),
    q_probable_25_out = quantile(age_in_years[ind_MSF_covid_status == "Probable" & merge_admit == "No"], c(0.25), na.rm = TRUE),
    q_probable_05_out = quantile(age_in_years[ind_MSF_covid_status == "Probable" & merge_admit == "No"], c(0.5), na.rm = TRUE),
    q_probable_75_out = quantile(age_in_years[ind_MSF_covid_status == "Probable" & merge_admit == "No"], c(0.75), na.rm = TRUE),
    f_probable_out    = format_med(q_probable_05_out, q_probable_25_out, q_probable_75_out),
    
    n_confirmed_out    = sum(ind_MSF_covid_status == "Confirmed" & merge_admit == "No", na.rm = TRUE),
    q_confirmed_25_out = quantile(age_in_years[ind_MSF_covid_status == "Confirmed" & merge_admit == "No"], c(0.25), na.rm = TRUE),
    q_confirmed_05_out = quantile(age_in_years[ind_MSF_covid_status == "Confirmed" & merge_admit == "No"], c(0.5), na.rm = TRUE),
    q_confirmed_75_out = quantile(age_in_years[ind_MSF_covid_status == "Confirmed" & merge_admit == "No"], c(0.75), na.rm = TRUE),
    f_confirmed_out    = format_med(q_confirmed_05_out, q_confirmed_25_out, q_confirmed_75_out)
  ) %>%
  select(-starts_with("q_"))


gtble6 <- tble6 %>%
  gt() %>%
  cols_label(
    country    = 'Country',
    project    = 'Project',
    n_patients = 'Visits',
    n_admis    = 'Admissions',
    
    n_probable_admis = 'N probable',
    f_probable_admis = 'Median age probable [IQR]',
    
    n_confirmed_admis = 'N confirmed',
    f_confirmed_admis = 'Median age confirmed [IQR]',
    
    n_probable_out = 'N probable',
    f_probable_out = 'Median age probable [IQR]',
    
    n_confirmed_out = 'N confirmed',
    f_confirmed_out = 'Median age confirmed [IQR]',
  ) %>%
  
  tab_spanner(
    label = 'Hospitalised',
    columns = ends_with("_admis")) %>%
  tab_spanner(
    label = 'Never hospitalised',
    columns = ends_with('_out')) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  cols_align(
    align = 'center',
    columns = everything()) %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)  %>%
  
  summary_rows(
    columns = starts_with("n_"),
    fns = list(Total = "sum"),
    decimals = 0)

gtsave(gtble6,
       file.path(path.local.msf.extra, paste0('gtble6', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble6 %>%
  tab_header(
    title = 'Median age stratified by gender, project and hospitalisation status')





## MSF_severity --------------------------------------------

tble14 <- dta_linelist_project %>%
  select(country, project, merge_admit, ind_MSF_covid_status, MSF_severity) %>%
  group_by(country, project) %>%
  summarise(
    n_suspected = sum(ind_MSF_covid_status == "Suspected", na.rm = TRUE),
    n_probable  = sum(ind_MSF_covid_status == "Probable", na.rm = TRUE),
    n_confirmed = sum(ind_MSF_covid_status == "Confirmed", na.rm = TRUE),
    
    n_admis = sum(merge_admit == "Yes", na.rm = TRUE),
    
    n_mild     = sum(MSF_severity == "Mild", na.rm = TRUE),
    n_moderate = sum(MSF_severity == "Moderate", na.rm = TRUE),
    n_severe   = sum(MSF_severity == "Severe", na.rm = TRUE),
    n_critical = sum(MSF_severity == "Critical", na.rm = TRUE),
    
    n_missing_MSF_severity = sum(is.na(MSF_severity)),
    
    n_patients = n())


gtble14 <- tble14 %>%
  gt() %>%
  cols_label(
    country    = 'Country',
    project    = 'Project',
    
    n_suspected = "Suspected",
    n_probable  = "Probable",
    n_confirmed = "Confirmed",
    
    n_admis = "Hospitalised",
    
    n_mild     = "Mild",
    n_moderate = "Moderate",
    n_severe   = "Severe",
    n_critical = "Critical",
    
    n_missing_MSF_severity = "Missing data MSF_severity",
    n_patients = "Total visits") %>%
  
  tab_spanner(
    label = 'Total presentation',
    columns = vars(n_suspected, n_probable, n_confirmed)) %>%
  tab_spanner(
    label = 'MSF_severity',
    columns = vars(n_mild, n_moderate, n_severe, n_critical)) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  cols_align(
    align = 'center',
    columns = everything()) %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)  %>%
  
  summary_rows(
    columns = starts_with("n_"),
    fns = list(Total = "sum"),
    decimals = 0)

gtsave(gtble14,
       file.path(path.local.msf.extra, paste0('gtble14', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble14 %>%
  tab_header(
    title = 'Case MSF_severity per project')



dta_linelist_project %>%
  filter(ind_outcome_patcourse_status == "Died") %>%
  filter(merge_admit == "Yes") %>%
  
  group_by(project, epi_week_admission, MSF_severity) %>%
  summarise(n = n()) %>%
  drop_na(epi_week_admission) %>%
  
  ggplot(aes(x = epi_week_admission,
             y = n,
             colour = MSF_severity)) +
  geom_line() +
  geom_point(alpha = 0.8,
             size = 2) +
  
  scale_x_date(name = "Week of Admission",
               date_breaks = "2 weeks",
               date_labels = "%V",
               sec.axis = ggplot2::sec_axis(trans = ~ .),
               expand = expansion(mult = c(0.01, 0.01))) +
  
  labs(x = "Week of admission",
       y = "Nb of death",
       title = glue::glue("Mortality by MSF_severity for hospitalized patients")) +
  ggthemes::scale_colour_tableau(name = "MSF_severity",
                                 palette = "Tableau 20")

ggsave(filename = paste0('mortality_MSF_severity', '_', week_report, '.png'),
       path = path.local.msf.extra,
       width = 10,
       height = 4,
       scale = 1.1,
       dpi = 320
)




tble15 <- dta_linelist_project %>%
  select(country, project, merge_admit, ind_MSF_covid_status, MSF_severity, ind_outcome_patcourse_status, merge_icu) %>%
  group_by(country, project) %>%
  summarise(
    n_suspected = sum(ind_MSF_covid_status == "Suspected" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
    n_probable  = sum(ind_MSF_covid_status == "Probable"  & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
    n_confirmed = sum(ind_MSF_covid_status == "Confirmed" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
    
    n_admis = sum(merge_admit == "Yes", na.rm = TRUE),
    
    n_mild     = sum(MSF_severity == "Mild", na.rm = TRUE),
    n_moderate = sum(MSF_severity == "Moderate", na.rm = TRUE),
    n_severe   = sum(MSF_severity == "Severe", na.rm = TRUE),
    n_critical = sum(MSF_severity == "Critical", na.rm = TRUE),
    
    n_deaths_icu = sum(ind_outcome_patcourse_status == "Died" & merge_icu == "Yes", na.rm = TRUE),
    
    n_patients = n())


gtble15 <- tble15 %>%
  gt() %>%
  cols_label(
    country    = 'Country',
    project    = 'Project',
    
    n_suspected = "Suspected",
    n_probable  = "Probable",
    n_confirmed = "Confirmed",
    
    n_admis = "Hospitalised",
    
    n_mild     = "Mild",
    n_moderate = "Moderate",
    n_severe   = "Severe",
    n_critical = "Critical",
    
    n_deaths_icu = "Death amond ICU patients",
    n_patients = "Total visits") %>%
  
  tab_spanner(
    label = 'Total presentation',
    columns = vars(n_suspected, n_probable, n_confirmed)) %>%
  tab_spanner(
    label = 'Death by MSF_severity',
    columns = vars(n_mild, n_moderate, n_severe, n_critical)) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  cols_align(
    align = 'center',
    columns = everything()) %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)  %>%
  
  summary_rows(
    columns = starts_with("n_"),
    fns = list(Total = "sum"),
    decimals = 0)

gtsave(gtble15,
       file.path(path.local.msf.extra, paste0('gtble15', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble15 %>%
  tab_header(
    title = 'Mortality by MSF_severity')



## Comorbidities -------------------------------------------

fig7 <- dta_linelist_project %>%
  filter(merge_admit == "Yes") %>%
  mutate(project = paste(country, project, sep = " - ")) %>%
  group_by(project) %>%
  summarise(
    n_hospi = n(),
    
    n_diabetes = sum(ind_Comcond_diabetes == "Yes", na.rm = TRUE),
    p_diabetes = n_diabetes / n_hospi,
    
    n_ind_MSF_hypertension  = sum(ind_MSF_hypertension == "Yes", na.rm = TRUE),
    p_ind_MSF_hypertension  = n_ind_MSF_hypertension / n_hospi,
    
    n_chronic_renal = sum(Comcond_renal == "Yes", na.rm = TRUE),
    p_chronic_renal = n_chronic_renal / n_hospi) %>%
  pivot_longer(cols = c(p_diabetes, p_ind_MSF_hypertension, p_chronic_renal),
               names_to = "Comorbidities",
               values_to = "percent_of_hospi",
               names_prefix = "p_") %>%
  filter(percent_of_hospi > 0) %>%
  
  ggplot(aes(x = project,
             y = percent_of_hospi,
             colour = Comorbidities)) +
  geom_point(size = 3,
             alpha = 0.8) +
  coord_flip() +
  facet_wrap(~Comorbidities, ncol = 1, scales = "free_y") +
  
  ggthemes::scale_colour_tableau(name = "Comorbidities",
                                 palette = "Tableau 20",
                                 breaks = c("diabetes", "ind_MSF_hypertension", "chronic_renal"),
                                 labels = c("Diabete", "Hypertension", "Renal chronic illness")) +
  
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  
  theme_light() +
  theme(legend.position = 'right',
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()) +
  
  labs(x = "",
       y = "Percentage of hospitalised patients",
       title = "Mortality and comorbidities")

ggsave(file.path(path.local.msf.extra, paste0('fig7', '_', week_report, '.png')),
       plot = fig7,
       width = 8,
       height = 14,
       scale = 1.1,
       dpi = 320)

fig7



list_comorb <- c("ind_MSF_ind_MSF_obesity", "ind_ind_Comcond_diabetes", "ind_MSF_hypertension", "ind_Comcond_renal")

tble16 <- dta_linelist_project %>%
  select(country, project, merge_admit, ind_Comcond_01, ind_Comcond_diabetes, ind_MSF_hypertension,
         ind_Comcond_renal, ind_outcome_patcourse_status, ind_MSF_obesity) %>%
  group_by(country, project) %>%
  summarise(
    n_all = n(), # Visits (cases) at project level
    
    n_comorb = sum(ind_Comcond_01 == 1, na.rm = TRUE), # at least one comorb (cases)
    p_comorb = n_comorb / n_all,
    a_comorb = format_nbp(n_comorb, p_comorb),
    
    n_comorb_hospi = sum(ind_Comcond_01 == 1 & merge_admit == "Yes", na.rm = TRUE), #hospitalised, at least one comorb
    p_comorb_hospi = n_comorb_hospi / n_comorb,
    a_comorb_hospi = format_nbp(n_comorb_hospi, p_comorb_hospi),
    
    n_comorb_death = sum(ind_Comcond_01 == 1 & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
    p_comorb_death = n_comorb_death / n_comorb_hospi,
    a_comorb_death = format_nbp(n_comorb_death, p_comorb_death),
    
    
    n_ind_MSF_obesity = sum(ind_MSF_obesity == "Yes", na.rm = TRUE),
    p_ind_MSF_obesity = n_ind_MSF_obesity / n_comorb,
    a_ind_MSF_obesity = format_nbp(n_ind_MSF_obesity, p_ind_MSF_obesity),
    
    n_ind_MSF_obesity_hospi = sum(ind_MSF_obesity == "Yes" & merge_admit == "Yes", na.rm = TRUE),
    p_ind_MSF_obesity_hospi = n_ind_MSF_obesity_hospi / n_ind_MSF_obesity,
    a_ind_MSF_obesity_hospi = format_nbp(n_ind_MSF_obesity_hospi, p_ind_MSF_obesity_hospi),
    
    n_ind_MSF_obesity_death = sum(ind_MSF_obesity == "Yes" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
    p_ind_MSF_obesity_death = n_ind_MSF_obesity_death / n_ind_MSF_obesity_hospi,
    a_ind_MSF_obesity_death = format_nbp(n_ind_MSF_obesity_death, p_ind_MSF_obesity_death),
    
    
    n_diabetes = sum(ind_Comcond_diabetes == "Yes", na.rm = TRUE),
    p_diabetes = n_diabetes / n_comorb,
    a_diabetes = format_nbp(n_diabetes, p_diabetes),
    
    n_diabetes_hospi = sum(ind_Comcond_diabetes == "Yes" & merge_admit == "Yes", na.rm = TRUE),
    p_diabetes_hospi = n_diabetes_hospi / n_diabetes,
    a_diabetes_hospi = format_nbp(n_diabetes_hospi, p_diabetes_hospi),
    
    n_diabetes_death = sum(ind_Comcond_diabetes == "Yes" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
    p_diabetes_death = n_diabetes_death / n_diabetes_hospi,
    a_diabetes_death = format_nbp(n_diabetes_death, p_diabetes_death),
    
    
    n_ind_MSF_hypertension  = sum(ind_MSF_hypertension == "Yes", na.rm = TRUE),
    p_ind_MSF_hypertension  = n_ind_MSF_hypertension / n_comorb,
    a_ind_MSF_hypertension  = format_nbp(n_ind_MSF_hypertension, p_ind_MSF_hypertension),
    
    n_ind_MSF_hypertension_hospi  = sum(ind_MSF_hypertension == "Yes" & merge_admit == "Yes", na.rm = TRUE),
    p_ind_MSF_hypertension_hospi  = n_ind_MSF_hypertension_hospi / n_ind_MSF_hypertension,
    a_ind_MSF_hypertension_hospi  = format_nbp(n_ind_MSF_hypertension_hospi, p_ind_MSF_hypertension_hospi),
    
    n_ind_MSF_hypertension_death  = sum(ind_MSF_hypertension == "Yes" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
    p_ind_MSF_hypertension_death  = n_ind_MSF_hypertension_death / n_ind_MSF_hypertension_hospi,
    a_ind_MSF_hypertension_death  = format_nbp(n_ind_MSF_hypertension_death, p_ind_MSF_hypertension_death),
    
    
    n_chronic_renal = sum(ind_Comcond_renal == "Yes", na.rm = TRUE),
    p_chronic_renal = n_chronic_renal / n_comorb,
    a_chronic_renal = format_nbp(n_chronic_renal, p_chronic_renal),
    
    n_chronic_renal_hospi = sum(ind_Comcond_renal == "Yes" & merge_admit == "Yes", na.rm = TRUE),
    p_chronic_renal_hospi = n_chronic_renal_hospi / n_chronic_renal,
    a_chronic_renal_hospi = format_nbp(n_chronic_renal_hospi, p_chronic_renal_hospi),
    
    n_chronic_renal_death = sum(ind_Comcond_renal == "Yes" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
    p_chronic_renal_death = n_chronic_renal_death / n_chronic_renal_hospi,
    a_chronic_renal_death = format_nbp(n_chronic_renal_death, p_chronic_renal_death)
  ) %>%
  select(country, project, starts_with("a_"))



gtble16 <- tble16 %>%
  gt() %>%
  cols_label(
    country    = 'Country',
    project    = 'Project',
    
    a_comorb       = 'N',
    a_comorb_hospi = 'Hospitalised',
    a_comorb_death = 'Deceased',
    
    a_ind_MSF_obesity       = 'N',
    a_ind_MSF_obesity_hospi = 'Hospitalised',
    a_ind_MSF_obesity_death = 'Deceased',
    
    a_diabetes       = 'N',
    a_diabetes_hospi = 'Hospitalised',
    a_diabetes_death = 'Deceased',
    
    a_ind_MSF_hypertension       = 'N',
    a_ind_MSF_hypertension_hospi = 'Hospitalised',
    a_ind_MSF_hypertension_death = 'Deceased',
    
    a_chronic_renal       = 'N',
    a_chronic_renal_hospi = 'Hospitalised',
    a_chronic_renal_death = 'Deceased') %>%
  
  tab_spanner(
    label = 'At least one documented comorbidity',
    columns = vars(a_comorb, a_comorb_hospi, a_comorb_death)) %>%
  tab_spanner(
    label = 'Obesity',
    columns = contains("_ind_MSF_obesity")) %>%
  tab_spanner(
    label = 'Diabete',
    columns = contains("_diabetes")) %>%
  tab_spanner(
    label = 'Hypertension',
    columns = contains("_ind_MSF_hypertension")) %>%
  tab_spanner(
    label = 'Chronic renal',
    columns = contains("_chronic_renal")) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  cols_align(
    align = 'center',
    columns = everything()) %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)

gtsave(gtble16,
       file.path(path.local.msf.extra, paste0('gtble16', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble16 %>%
  tab_header(
    title = 'Number of patients with comorbidities and proportion of hospitalizations and deaths')





## Coinfections --------------------------------------------

fig8 <- dta_linelist_project %>%
  filter(merge_admit == "Yes") %>%
  select(country, project, merge_admit, ind_outcome_patcourse_status, ind_MSF_malaria, ind_MSF_hiv_status, ind_MSF_tb_active,
         ind_MSF_tb_treatment_past, ind_MSF_malnutrition) %>%
  mutate(project = paste(country, project, sep = " - ")) %>%
  group_by(project) %>%
  summarise(
    n_hospi =  n(),
    
    n_ind_MSF_malaria   = sum(ind_MSF_malaria == "Yes", na.rm = TRUE),
    n_hiv       = sum(ind_MSF_hiv_status == "Yes", na.rm = TRUE),
    n_ind_MSF_tb_active = sum(ind_MSF_tb_active == "Yes", na.rm = TRUE),
    n_tb_past   = sum(ind_MSF_tb_treatment_past == "Yes", na.rm = TRUE),
    
    p_ind_MSF_malaria   = n_ind_MSF_malaria / n_hospi,
    p_hiv       = n_hiv / n_hospi,
    p_ind_MSF_tb_active = n_ind_MSF_tb_active / n_hospi,
    p_tb_past   = n_tb_past / n_hospi
  ) %>%
  
  pivot_longer(cols = c(p_ind_MSF_malaria, p_hiv, p_ind_MSF_tb_active, p_tb_past),
               names_to = "Coinfection",
               values_to = "percent_of_hospi",
               names_prefix = "p_") %>%
  filter(percent_of_hospi > 0) %>%
  
  
  ggplot(aes(x = project,
             y = percent_of_hospi,
             colour = Coinfection)) +
  geom_point(size = 3,
             alpha = 0.8) +
  coord_flip() +
  facet_wrap(~Coinfection, ncol = 2, scales = "free_y") +
  
  ggthemes::scale_colour_tableau(name = "Coinfection",
                                 palette = "Tableau 20",
                                 breaks = c("hiv", "ind_MSF_malaria", "ind_MSF_tb_active", "tb_past"),
                                 labels = c("HIV", "Malaria", "TB active", "TB in the past")) +
  
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  
  
  theme_light() +
  theme(legend.position = 'right',
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()) +
  labs(x = "",
       y = "Percentage of hospitalised patients",
       title = "Coinfections in hospitalised patients")




ggsave(file.path(path.local.msf.extra, paste0('fig8', '_', week_report, '.png')),
       plot = fig8,
       width = 10,
       height = 10,
       scale = 1.1,
       dpi = 320)

fig8





list_coinf <- c("ind_MSF_malaria", "ind_MSF_hiv_status", "ind_MSF_tb_active", "ind_MSF_tb_treatment_past", "ind_MSF_malnutrition")

tble17 <-dta_linelist_project %>%
  select(country, project, merge_admit, ind_outcome_patcourse_status, ind_MSF_malaria, ind_MSF_hiv_status,
         ind_MSF_tb_active, ind_MSF_tb_treatment_past, ind_MSF_malnutrition) %>%
  group_by(country, project) %>%
  mutate(coinf = ifelse(ind_MSF_malaria == "Yes" | ind_MSF_hiv_status == "Yes" | ind_MSF_tb_active == "Yes" |
                          ind_MSF_tb_treatment_past == "Yes" | ind_MSF_malnutrition == "Yes",
                        1, 0)) %>%
  summarise(n_coinf = sum(coinf == 1, na.rm = TRUE),
            p_coinf = n_coinf / n(),
            a_coinf = format_nbp(n_coinf, p_coinf),
            
            n_coinf_hospi = sum(coinf == 1 & merge_admit == "Yes", na.rm = TRUE),
            p_coinf_hospi = n_coinf_hospi / n_coinf,
            a_coinf_hospi = format_nbp(n_coinf_hospi, p_coinf_hospi),
            
            n_coinf_death = sum(coinf == 1 & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
            p_coinf_death = n_coinf_death / n_coinf,
            a_coinf_death = format_nbp(n_coinf_death, p_coinf_death),
            
            
            n_ind_MSF_malaria = sum(ind_MSF_malaria == "Yes", na.rm = TRUE),
            p_ind_MSF_malaria = n_ind_MSF_malaria / n_coinf,
            a_ind_MSF_malaria = format_nbp(n_ind_MSF_malaria, p_ind_MSF_malaria),
            
            n_ind_MSF_malaria_hospi = sum(ind_MSF_malaria == "Yes" & merge_admit == "Yes", na.rm = TRUE),
            p_ind_MSF_malaria_hospi = n_ind_MSF_malaria_hospi / n_ind_MSF_malaria,
            a_ind_MSF_malaria_hospi = format_nbp(n_ind_MSF_malaria_hospi, p_ind_MSF_malaria_hospi),
            
            n_ind_MSF_malaria_death = sum(ind_MSF_malaria == "Yes" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
            p_ind_MSF_malaria_death = n_ind_MSF_malaria_death / n_ind_MSF_malaria,
            a_ind_MSF_malaria_death = format_nbp(n_ind_MSF_malaria_death, p_ind_MSF_malaria_death),
            
            
            n_hiv = sum(ind_MSF_hiv_status == "Yes", na.rm = TRUE),
            p_hiv = n_hiv / n_coinf,
            a_hiv = format_nbp(n_hiv, p_hiv),
            
            n_hiv_hospi = sum(ind_MSF_hiv_status == "Yes" & merge_admit == "Yes", na.rm = TRUE),
            p_hiv_hospi = n_hiv_hospi / n_hiv,
            a_hiv_hospi = format_nbp(n_hiv_hospi, p_hiv_hospi),
            
            n_hiv_death = sum(ind_MSF_hiv_status == "Yes" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
            p_hiv_death = n_hiv_death / n_hiv,
            a_hiv_death = format_nbp(n_hiv_death, p_hiv_death),
            
            
            n_ind_MSF_tb_active = sum(ind_MSF_tb_active == "Yes", na.rm = TRUE),
            p_ind_MSF_tb_active = n_ind_MSF_tb_active / n_coinf,
            a_ind_MSF_tb_active = format_nbp(n_ind_MSF_tb_active, p_ind_MSF_tb_active),
            
            n_ind_MSF_tb_active_hospi = sum(ind_MSF_tb_active == "Yes" & merge_admit == "Yes", na.rm = TRUE),
            p_ind_MSF_tb_active_hospi = n_ind_MSF_tb_active_hospi / n_ind_MSF_tb_active,
            a_ind_MSF_tb_active_hospi = format_nbp(n_ind_MSF_tb_active_hospi, p_ind_MSF_tb_active_hospi),
            
            n_ind_MSF_tb_active_death = sum(ind_MSF_tb_active == "Yes" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
            p_ind_MSF_tb_active_death = n_ind_MSF_tb_active_death / n_ind_MSF_tb_active,
            a_ind_MSF_tb_active_death = format_nbp(n_ind_MSF_tb_active_death, p_ind_MSF_tb_active_death),
            
            
            n_tb_past = sum(ind_MSF_tb_treatment_past == "Yes", na.rm = TRUE),
            p_tb_past = n_tb_past / n_coinf,
            a_tb_past = format_nbp(n_tb_past, p_tb_past),
            
            n_tb_past_hospi = sum(ind_MSF_tb_treatment_past == "Yes" & merge_admit == "Yes", na.rm = TRUE),
            p_tb_past_hospi = n_tb_past_hospi / n_tb_past,
            a_tb_past_hospi = format_nbp(n_tb_past_hospi, p_tb_past_hospi),
            
            n_tb_past_death = sum(ind_MSF_tb_treatment_past == "Yes" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
            p_tb_past_death = n_tb_past_death / n_tb_past,
            a_tb_past_death = format_nbp(n_tb_past_death, p_tb_past_death),
            
            n_ind_MSF_malnutrition = sum(ind_MSF_malnutrition == "Yes", na.rm = TRUE),
            p_ind_MSF_malnutrition = n_ind_MSF_malnutrition / n_coinf,
            a_ind_MSF_malnutrition = format_nbp(n_ind_MSF_malnutrition, p_ind_MSF_malnutrition),
            
            n_ind_MSF_malnutrition_hospi = sum(ind_MSF_malnutrition == "Yes" & merge_admit == "Yes", na.rm = TRUE),
            p_ind_MSF_malnutrition_hospi = n_ind_MSF_malnutrition_hospi / n_ind_MSF_malnutrition,
            a_ind_MSF_malnutrition_hospi = format_nbp(n_ind_MSF_malnutrition_hospi, p_ind_MSF_malnutrition_hospi),
            
            n_ind_MSF_malnutrition_death = sum(ind_MSF_malnutrition == "Yes" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
            p_ind_MSF_malnutrition_death = n_ind_MSF_malnutrition_death / n_ind_MSF_malnutrition,
            a_ind_MSF_malnutrition_death = format_nbp(n_ind_MSF_malnutrition_death, p_ind_MSF_malnutrition_death),
            
  )

gtble17 <- tble17 %>%
  select(country, project, starts_with("a_"))  %>%
  gt() %>%
  cols_label(
    country    = 'Country',
    project    = 'Project',
    
    a_coinf       = 'N' ,
    a_coinf_hospi = 'Hospitalised',
    a_coinf_death = 'Deceased',
    
    a_ind_MSF_malaria       = 'N' ,
    a_ind_MSF_malaria_hospi = 'Hospitalised',
    a_ind_MSF_malaria_death = 'Deceased',
    
    a_hiv       = 'N',
    a_hiv_hospi = 'Hospitalised',
    a_hiv_death = 'Deceased',
    
    a_ind_MSF_tb_active       = 'N',
    a_ind_MSF_tb_active_hospi = 'Hospitalised',
    a_ind_MSF_tb_active_death = 'Deceased',
    
    a_tb_past        = 'N',
    a_tb_past_hospi  = 'Hospitalised',
    a_tb_past_death = 'Deceased',
    
    a_ind_MSF_malnutrition       = 'N',
    a_ind_MSF_malaria_hospi      = 'Hospitalised',
    a_ind_MSF_malnutrition_death = 'Deceased') %>%
  
  tab_spanner(
    label = 'At least one documented co-infection',
    columns = vars(a_coinf, a_coinf_hospi, a_coinf_death)) %>%
  tab_spanner(
    label = 'Malaria',
    columns = contains("_ind_MSF_malaria")) %>%
  tab_spanner(
    label = 'HIV',
    columns = contains("_hiv")) %>%
  tab_spanner(
    label = 'Tuberculosis active',
    columns = contains("_ind_MSF_tb_active")) %>%
  tab_spanner(
    label = 'Tuberculosis treatment in the past',
    columns = contains("_tb_past")) %>%
  tab_spanner(
    label = 'Malnutrition',
    columns = contains("_ind_MSF_malnutrition")) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  cols_align(
    align = 'center',
    columns = everything()) %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)

gtsave(gtble17,
       file.path(path.local.msf.extra, paste0('gtble17', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble17 %>%
  tab_header(
    title = 'Number of patients with coinfections and proportion of hospitalizations and death')







## Intervention received -----------------------------------

### ICU ----------------------------------------------------

tble7 <- dta_linelist_project %>%
  select(country, project, merge_admit, patcourse_icu, merge_icu) %>%
  group_by(country, project) %>%
  summarise(
    n_patients = n(),
    n_admis    = sum(merge_admit == "Yes", na.rm = TRUE),
    
    n_icu_admission = sum(merge_admit == "Yes" & patcourse_icu == "Yes", na.rm = TRUE),
    p_icu_admission = n_icu_admission / n_admis,
    m_icu_admission = format_nbp(n_icu_admission, p_icu_admission),
    
    n_icu_later  = sum(merge_admit == "Yes" & patcourse_icu != "Yes" & merge_icu == "Yes", na.rm = TRUE),
    p_icu_later = n_icu_later / n_admis,
    m_icu_later = format_nbp(n_icu_later, p_icu_later)
  ) %>%
  select(country, project, n_patients, n_admis,
         m_icu_admission,  m_icu_later)



gtble7 <-  tble7 %>%
  gt() %>%
  cols_label(
    country    = 'Country',
    project    = 'Project',
    n_patients = 'Visits',
    n_admis    = 'Admissions',
    
    m_icu_admission = 'ICU at adm.',
    m_icu_later     = 'ICU later',
  ) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  cols_align(
    align = 'center',
    columns = everything()) %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)  %>%
  
  summary_rows(
    columns = starts_with("n_"),
    fns = list(Total = "sum"),
    decimals = 0)

gtsave(gtble7,
       file.path(path.local.msf.extra, paste0('gtble7', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble7 %>%
  tab_header(
    title = 'Total number of patient visits, admitted, and admitted in ICU')




tble8 <- dta_linelist_project %>%
  select(country, project, ind_MSF_covid_status, merge_admit, patcourse_icu, merge_icu) %>%
  group_by(country, project) %>%
  summarise(
    n_patients = n(),
    n_admis    = sum(merge_admit == "Yes", na.rm = TRUE),
    
    n_probable            = sum(ind_MSF_covid_status == "Probable", na.rm = TRUE),
    n_probable_admis      = sum(ind_MSF_covid_status == "Probable" & merge_admit == "Yes", na.rm = TRUE),
    p_probable_admis      = n_probable_admis / n_probable,
    m_probable_admis      = format_nbp(n_probable_admis, p_probable_admis),
    
    n_probable_icu_admis  = sum(ind_MSF_covid_status == "Probable" & merge_admit == "Yes" & patcourse_icu == "Yes", na.rm = TRUE),
    p_probable_icu_admis  = n_probable_icu_admis / n_probable_admis,
    m_probable_icu_admis  = format_nbp(n_probable_icu_admis, p_probable_icu_admis),
    
    n_probable_icu_later  = sum(ind_MSF_covid_status == "Probable" & merge_admit == "Yes" & patcourse_icu != "Yes" & merge_icu == "Yes", na.rm = TRUE),
    p_probable_icu_later  = n_probable_icu_later / n_probable_admis,
    m_probable_icu_later  = format_nbp(n_probable_icu_later, p_probable_icu_later),
    
    n_suspected            = sum(ind_MSF_covid_status == "Suspected", na.rm = TRUE),
    n_suspected_admis      = sum(ind_MSF_covid_status == "Suspected" & merge_admit == "Yes", na.rm = TRUE),
    p_suspected_admis      = n_suspected_admis / n_suspected,
    m_suspected_admis      = format_nbp(n_suspected_admis, p_suspected_admis),
    
    n_suspected_icu_admis  = sum(ind_MSF_covid_status == "Suspected" & merge_admit == "Yes" & patcourse_icu == "Yes", na.rm = TRUE),
    p_suspected_icu_admis  = n_suspected_icu_admis / n_suspected_admis,
    m_suspected_icu_admis  = format_nbp(n_suspected_icu_admis, p_suspected_icu_admis),
    
    n_suspected_icu_later  = sum(ind_MSF_covid_status == "Suspected" & merge_admit == "Yes" & patcourse_icu != "Yes" & merge_icu == "Yes", na.rm = TRUE),
    p_suspected_icu_later  = n_suspected_icu_later / n_suspected_admis,
    m_suspected_icu_later  = format_nbp(n_suspected_icu_later, p_suspected_icu_later),
    
    n_confirmed            = sum(ind_MSF_covid_status == "Confirmed", na.rm = TRUE),
    n_confirmed_admis      = sum(ind_MSF_covid_status == "Confirmed" & merge_admit == "Yes", na.rm = TRUE),
    p_confirmed_admis      = n_confirmed_admis / n_confirmed,
    m_confirmed_admis      = format_nbp(n_confirmed_admis, p_confirmed_admis),
    
    n_confirmed_icu_admis  = sum(ind_MSF_covid_status == "Confirmed" & merge_admit == "Yes" & patcourse_icu == "Yes", na.rm = TRUE),
    p_confirmed_icu_admis  = n_confirmed_icu_admis / n_confirmed_admis,
    m_confirmed_icu_admis  = format_nbp(n_confirmed_icu_admis, p_confirmed_icu_admis),
    
    n_confirmed_icu_later  = sum(ind_MSF_covid_status == "Confirmed" & merge_admit == "Yes" & patcourse_icu != "Yes" & merge_icu == "Yes", na.rm = TRUE),
    p_confirmed_icu_later  = n_confirmed_icu_later / n_confirmed_admis,
    m_confirmed_icu_later  = format_nbp(n_confirmed_icu_later, p_confirmed_icu_later),
  ) %>%
  select(country, project, n_patients,
         # n_admis,
         n_probable,  m_probable_admis,  m_probable_icu_admis,  m_probable_icu_later,
         n_suspected, m_suspected_admis, m_suspected_icu_admis, m_suspected_icu_later,
         n_confirmed, m_confirmed_admis, m_confirmed_icu_admis, m_confirmed_icu_later)




gtble8 <-  tble8 %>%
  gt() %>%
  cols_label(
    country          = 'Country',
    project          = 'Project',
    n_patients       = 'Visits',
    # n_admited        = 'Admissions',
    
    n_probable            = 'Visits',
    m_probable_admis      = 'Hospit.',
    m_probable_icu_admis  = 'ICU at adm.',
    m_probable_icu_later  = 'ICU after adm.',
    
    n_suspected            = 'Visits',
    m_suspected_admis      = 'Hospit.',
    m_suspected_icu_admis  = 'ICU at adm.',
    m_suspected_icu_later  = 'ICU after adm.',
    
    n_confirmed            = 'Visits',
    m_confirmed_admis      = 'Hospit.',
    m_confirmed_icu_admis  = 'ICU at adm.',
    m_confirmed_icu_later  = 'ICU after adm.') %>%
  
  tab_spanner(
    label = 'Probable',
    columns = contains("_probable")) %>%
  tab_spanner(
    label = 'Suspected',
    columns = contains('_suspected')) %>%
  tab_spanner(
    label = 'Confirmed',
    columns = contains('_confirmed')) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  cols_align(
    align = 'center',
    columns = everything()) %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)  %>%
  
  summary_rows(
    columns = starts_with("n_"),
    fns = list(Total = "sum"),
    decimals = 0)

gtsave(gtble8,
       file.path(path.local.msf.extra, paste0('gtble8', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble8 %>%
  tab_header(
    title = 'Total number of patient visits by case status and ICU admission status')



### Oxygen -------------------------------------------------

tble9 <- dta_linelist_project %>%
  select(country, project, merge_admit, MSF_received_oxygen, merge_oxygen) %>%
  group_by(country, project) %>%
  summarise(
    n_patients = n(),
    n_admis    = sum(merge_admit == "Yes", na.rm = TRUE),
    
    n_oxygen_admission = sum(merge_admit == "Yes" & MSF_received_oxygen == "Yes", na.rm = TRUE),
    p_oxygen_admission = n_oxygen_admission / n_admis,
    m_oxygen_admission = format_nbp(n_oxygen_admission, p_oxygen_admission),
    
    n_oxygen_later  = sum(merge_admit == "Yes" & MSF_received_oxygen != "Yes" & merge_oxygen == "Yes", na.rm = TRUE),
    p_oxygen_later  = n_oxygen_later / n_admis,
    m_oxygen_later  = format_nbp(n_oxygen_later, p_oxygen_later)
  ) %>%
  select(country, project, n_patients, n_admis,
         m_oxygen_admission,  m_oxygen_later)




gtble9 <-  tble9 %>%
  gt() %>%
  cols_label(
    country    = 'Country',
    project    = 'Project',
    n_patients = 'Visits',
    n_admis    = 'Admissions',
    
    m_oxygen_admission = 'Oxygen at adm.',
    m_oxygen_later     = 'Oxygen later',
  ) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  cols_align(
    align = 'center',
    columns = everything()) %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)  %>%
  
  summary_rows(
    columns = starts_with("n_"),
    fns = list(Total = "sum"),
    decimals = 0)

gtsave(gtble9,
       file.path(path.local.msf.extra, paste0('gtble9', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble9 %>%
  tab_header(
    title = 'Total number of patient visits and oxygen status')



tble10 <- dta_linelist_project %>%
  select(country, project, ind_MSF_covid_status, merge_admit, MSF_received_oxygen, merge_oxygen) %>%
  group_by(country, project) %>%
  summarise(
    n_patients = n(),
    n_admis    = sum(merge_admit == "Yes", na.rm = TRUE),
    
    n_probable            = sum(ind_MSF_covid_status == "Probable", na.rm = TRUE),
    n_probable_admis      = sum(ind_MSF_covid_status == "Probable" & merge_admit == "Yes", na.rm = TRUE),
    p_probable_admis      =  n_probable_admis / n_probable,
    m_probable_admis         = format_nbp(n_probable_admis, p_probable_admis),
    
    n_probable_oxygen_admis  = sum(ind_MSF_covid_status == "Probable" & merge_admit == "Yes" & MSF_received_oxygen == "Yes", na.rm = TRUE),
    p_probable_oxygen_admis  = n_probable_oxygen_admis / n_probable_admis,
    m_probable_oxygen_admis  = format_nbp(n_probable_oxygen_admis, p_probable_oxygen_admis),
    
    n_probable_oxygen_later  = sum(ind_MSF_covid_status == "Probable" & merge_admit == "Yes" & MSF_received_oxygen != "Yes" & merge_oxygen == "Yes", na.rm = TRUE),
    p_probable_oxygen_later  = n_probable_oxygen_later / n_probable_admis,
    m_probable_oxygen_later  = format_nbp(n_probable_oxygen_later, p_probable_oxygen_later),
    
    n_suspected            = sum(ind_MSF_covid_status == "Suspected", na.rm = TRUE),
    n_suspected_admis      = sum(ind_MSF_covid_status == "Suspected" & merge_admit == "Yes", na.rm = TRUE),
    p_suspected_admis      = n_suspected_admis / n_suspected,
    m_suspected_admis      = format_nbp(n_suspected_admis, p_suspected_admis),
    
    n_suspected_oxygen_admis  = sum(ind_MSF_covid_status == "Suspected" & merge_admit == "Yes" & MSF_received_oxygen == "Yes", na.rm = TRUE),
    p_suspected_oxygen_admis  = n_suspected_oxygen_admis / n_suspected_admis,
    m_suspected_oxygen_admis  = format_nbp(n_suspected_oxygen_admis, p_suspected_oxygen_admis),
    
    n_suspected_oxygen_later  = sum(ind_MSF_covid_status == "Suspected" & merge_admit == "Yes" & MSF_received_oxygen != "Yes" & merge_oxygen == "Yes", na.rm = TRUE),
    p_suspected_oxygen_later  = n_suspected_oxygen_later / n_suspected_admis,
    m_suspected_oxygen_later  = format_nbp(n_suspected_oxygen_later, p_suspected_oxygen_later),
    
    
    n_confirmed            = sum(ind_MSF_covid_status == "Confirmed", na.rm = TRUE),
    n_confirmed_admis      = sum(ind_MSF_covid_status == "Confirmed" & merge_admit == "Yes", na.rm = TRUE),
    p_confirmed_admis      = n_confirmed_admis / n_confirmed,
    m_confirmed_admis      = format_nbp(n_confirmed_admis, p_confirmed_admis),
    
    n_confirmed_oxygen_admis  = sum(ind_MSF_covid_status == "Confirmed" & merge_admit == "Yes" & MSF_received_oxygen == "Yes", na.rm = TRUE),
    p_confirmed_oxygen_admis  = n_confirmed_oxygen_admis / n_confirmed_admis,
    m_confirmed_oxygen_admis  = format_nbp(n_confirmed_oxygen_admis, p_confirmed_oxygen_admis),
    
    n_confirmed_oxygen_later  = sum(ind_MSF_covid_status == "Confirmed" & merge_admit == "Yes" & MSF_received_oxygen != "Yes" & merge_oxygen == "Yes", na.rm = TRUE),
    p_confirmed_oxygen_later  = n_confirmed_oxygen_later / n_confirmed_admis,
    m_confirmed_oxygen_later  = format_nbp(n_confirmed_oxygen_later, p_confirmed_oxygen_later),
  ) %>%
  select(country, project, n_patients,
         n_probable,  m_probable_admis,  m_probable_oxygen_admis,  m_probable_oxygen_later,
         n_suspected, m_suspected_admis, m_suspected_oxygen_admis, m_suspected_oxygen_later,
         n_confirmed, m_confirmed_admis, m_confirmed_oxygen_admis, m_confirmed_oxygen_later)



gtble10 <- tble10 %>%
  gt() %>%
  cols_label(
    country          = 'Country',
    project          = 'Project',
    n_patients       = 'Visits',
    
    n_probable               = 'Visits',
    m_probable_admis         = 'Hospit.',
    m_probable_oxygen_admis  = 'Oxygen at adm.',
    m_probable_oxygen_later  = 'Oxygen after adm.',
    
    n_suspected               = 'Visits',
    m_suspected_admis         = 'Hospit.',
    m_suspected_oxygen_admis  = 'Oxygen at adm.',
    m_suspected_oxygen_later  = 'Oxygen after adm.',
    
    n_confirmed               = 'Visits',
    m_confirmed_admis         = 'Hospit.',
    m_confirmed_oxygen_admis  = 'Oxygen at adm.',
    m_confirmed_oxygen_later  = 'Oxygen after adm.') %>%
  
  tab_spanner(
    label = 'Probable',
    columns = contains("_probable")) %>%
  tab_spanner(
    label = 'Suspected',
    columns = contains('_suspected')) %>%
  tab_spanner(
    label = 'Confirmed',
    columns = contains('_confirmed')) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  cols_align(
    align = 'center',
    columns = everything()) %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)  %>%
  
  summary_rows(
    columns = starts_with("n_"),
    fns = list(Total = "sum"),
    decimals = 0)


gtsave(gtble10,
       file.path(path.local.msf.extra, paste0('gtble10', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble10 %>%
  tab_header(
    title = 'Total number of patient visits by case status and received_oxygen admission status')





### Ventilation --------------------------------------------

tble12 <- dta_linelist_project %>%
  select(country, project, merge_admit, patcourse_vent, merge_vent) %>%
  group_by(country, project) %>%
  summarise(
    n_patients = n(),
    n_admis    = sum(merge_admit == "Yes", na.rm = TRUE),
    
    n_vent_admission = sum(merge_admit == "Yes" & patcourse_vent == "Yes", na.rm = TRUE),
    p_vent_admission = n_vent_admission / n_admis,
    m_vent_admission = format_nbp(n_vent_admission, p_vent_admission),
    
    n_vent_later  = sum(merge_admit == "Yes" & patcourse_vent != "Yes" & merge_vent == "Yes", na.rm = TRUE),
    p_vent_later  = n_vent_later / n_admis,
    m_vent_later  = format_nbp(n_vent_later, p_vent_later)
  ) %>%
  select(country, project, n_patients, n_admis,
         m_vent_admission,  m_vent_later)


gtble12 <-  tble12 %>%
  gt() %>%
  cols_label(
    country    = 'Country',
    project    = 'Project',
    n_patients = 'Visits',
    n_admis    = 'Admissions',
    
    m_vent_admission = 'Ventilation at adm.',
    m_vent_later     = 'Ventilation later',
  ) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  cols_align(
    align = 'center',
    columns = everything()) %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)  %>%
  
  summary_rows(
    columns = starts_with("n_"),
    fns = list(Total = "sum"),
    decimals = 0)

gtsave(gtble12,
       file.path(path.local.msf.extra, paste0('gtble12', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble12 %>%
  tab_header(
    title = 'Total number of patient visits and ventilation status')




tble13 <- dta_linelist_project %>%
  select(country, project, ind_MSF_covid_status, merge_admit, patcourse_vent, merge_vent) %>%
  group_by(country, project) %>%
  summarise(
    n_patients = n(),
    n_admis    = sum(merge_admit == "Yes", na.rm = TRUE),
    
    n_probable            = sum(ind_MSF_covid_status == "Probable", na.rm = TRUE),
    n_probable_admis      = sum(ind_MSF_covid_status == "Probable" & merge_admit == "Yes", na.rm = TRUE),
    p_probable_admis      = n_probable_admis / n_probable,
    m_probable_admis      = format_nbp(n_probable_admis, p_probable_admis),
    
    n_probable_vent_admis  = sum(ind_MSF_covid_status == "Probable" & merge_admit == "Yes" & patcourse_vent == "Yes", na.rm = TRUE),
    p_probable_vent_admis  = n_probable_vent_admis / n_probable_admis,
    m_probable_vent_admis  = format_nbp(n_probable_vent_admis, p_probable_vent_admis),
    
    n_probable_vent_later  = sum(ind_MSF_covid_status == "Probable" & merge_admit == "Yes" & patcourse_vent != "Yes" & merge_vent == "Yes", na.rm = TRUE),
    p_probable_vent_later  = n_probable_vent_later / n_probable_admis,
    m_probable_vent_later  = format_nbp(n_probable_vent_later, p_probable_vent_later),
    
    n_suspected            = sum(ind_MSF_covid_status == "Suspected", na.rm = TRUE),
    n_suspected_admis      = sum(ind_MSF_covid_status == "Suspected" & merge_admit == "Yes", na.rm = TRUE),
    p_suspected_admis      = n_suspected_admis / n_suspected,
    m_suspected_admis      = format_nbp(n_suspected_admis, p_suspected_admis),
    
    n_suspected_vent_admis  = sum(ind_MSF_covid_status == "Suspected" & merge_admit == "Yes" & patcourse_vent == "Yes", na.rm = TRUE),
    p_suspected_vent_admis  = n_suspected_vent_admis / n_suspected_admis,
    m_suspected_vent_admis  = format_nbp(n_suspected_vent_admis, p_suspected_vent_admis),
    
    n_suspected_vent_later  = sum(ind_MSF_covid_status == "Suspected" & merge_admit == "Yes" & patcourse_vent != "Yes" & merge_vent == "Yes", na.rm = TRUE),
    p_suspected_vent_later  = n_suspected_vent_later / n_suspected_admis,
    m_suspected_vent_later  = format_nbp(n_suspected_vent_later, p_suspected_vent_later),
    
    
    n_confirmed            = sum(ind_MSF_covid_status == "Confirmed", na.rm = TRUE),
    n_confirmed_admis      = sum(ind_MSF_covid_status == "Confirmed" & merge_admit == "Yes", na.rm = TRUE),
    p_confirmed_admis      = n_confirmed_admis / n_confirmed,
    m_confirmed_admis      = format_nbp(n_confirmed_admis, p_confirmed_admis),
    
    n_confirmed_vent_admis  = sum(ind_MSF_covid_status == "Confirmed" & merge_admit == "Yes" & patcourse_vent == "Yes", na.rm = TRUE),
    p_confirmed_vent_admis  = n_confirmed_vent_admis / n_confirmed_admis,
    m_confirmed_vent_admis  = format_nbp(n_confirmed_vent_admis, p_confirmed_vent_admis),
    
    n_confirmed_vent_later  = sum(ind_MSF_covid_status == "Confirmed" & merge_admit == "Yes" & patcourse_vent != "Yes" & merge_vent == "Yes", na.rm = TRUE),
    p_confirmed_vent_later  = n_confirmed_vent_later / n_confirmed_admis,
    m_confirmed_vent_later  = format_nbp(n_confirmed_vent_later, p_confirmed_vent_later),
  ) %>%
  select(country, project, n_patients,
         n_probable,  m_probable_admis,  m_probable_vent_admis,  m_probable_vent_later,
         n_suspected, m_suspected_admis, m_suspected_vent_admis, m_suspected_vent_later,
         n_confirmed, m_confirmed_admis, m_confirmed_vent_admis, m_confirmed_vent_later)



gtble13 <- tble13 %>%
  gt() %>%
  cols_label(
    country    = 'Country',
    project    = 'Project',
    n_patients = 'Visits',
    
    n_probable             = 'Visits',
    m_probable_admis       = 'Hospit.',
    m_probable_vent_admis  = 'Ventilation at adm.',
    m_probable_vent_later  = 'Ventilation after adm.',
    
    n_suspected             = 'Visits',
    m_suspected_admis       = 'Hospit.',
    m_suspected_vent_admis  = 'Ventilation at adm.',
    m_suspected_vent_later  = 'Ventilation after adm.',
    
    n_confirmed             = 'Visits',
    m_confirmed_admis       = 'Hospit.',
    m_confirmed_vent_admis  = 'Ventilation at adm.',
    m_confirmed_vent_later  = 'Ventilation after adm.') %>%
  
  tab_spanner(
    label = 'Probable',
    columns = contains("_probable")) %>%
  tab_spanner(
    label = 'Suspected',
    columns = contains('_suspected')) %>%
  tab_spanner(
    label = 'Confirmed',
    columns = contains('_confirmed')) %>%
  
  fmt_missing(
    columns = starts_with('n_'),
    missing_text = "0") %>%
  
  cols_align(
    align = 'center',
    columns = everything()) %>%
  
  tab_options(
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold",
    data_row.padding = px(2),
    row_group.padding = px(2),
    row.striping.include_table_body = TRUE)  %>%
  
  summary_rows(
    columns = starts_with("n_"),
    fns = list(Total = "sum"),
    decimals = 0)


gtsave(gtble13,
       file.path(path.local.msf.extra, paste0('gtble13', '_', week_report, '.html')),
       inline_css = TRUE) %>%
  invisible()


gtble13 %>%
  tab_header(
    title = 'Total number of patient visits by case status and ventilation status')




### Mortality by intervention received ---------------------

fig6 <- dta_linelist_project %>%
  filter(merge_admit == "Yes") %>%
  
  group_by(continent, country, project) %>%
  
  summarise(
    n_admit = n(),
    
    n_oxy       = sum(merge_oxygen == "Yes", na.rm = TRUE),
    n_death_oxy = sum(merge_oxygen == "Yes" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
    p_Oxygen    = round(100 * n_death_oxy / n_oxy, 1),
    
    n_vent        = sum(merge_vent == "Yes", na.rm = TRUE),
    n_death_vent  = sum(merge_vent == "Yes" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
    p_Ventilated = round(100 * n_death_vent / n_vent, 1),
    
    n_icu       = sum(merge_icu == "Yes", na.rm = TRUE),
    n_death_icu = sum(merge_icu == "Yes" & ind_outcome_patcourse_status == "Died", na.rm = TRUE),
    p_ICU       = round(100 * n_death_icu / n_icu, 1)
  ) %>%
  mutate(project = paste(country, project, sep = " - ")) %>%
  pivot_longer(cols = c(p_Oxygen, p_Ventilated, p_ICU),
               names_to = "therapy",
               names_prefix = "p_",
               values_to = "mortality") %>%
  mutate(therapy = factor(therapy,
                          levels = c("Oxygen", "Ventilated", "ICU")))  %>%
  
  ggplot(aes(x = reorder(project, desc(country)),
             y = mortality,
             size = n_admit,
             colour = therapy)) +
  geom_point(alpha = 0.8,
             position = position_dodge2(0.2)) +
  coord_flip() +
  facet_wrap(~therapy, ncol = 3, scales = "free") +
  labs(x = "",
       y = "Mortality (% of deceased among cases)",
       title = "Mortality by therapy received, by project") +
  
  ggthemes::scale_colour_tableau(name = "Therapy received", palette = "Tableau 20") +
  
  scale_size_continuous(name = "Number of hosp. cases\nin project",
                        # breaks = c(10, 100, 1000, 4000, 6000)
  ) +
  
  theme_light() +
  theme(legend.position = 'right',
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())


ggsave(file.path(path.local.msf.extra, paste0('fig6', '_', week_report, '.png')),
       plot = fig6,
       width = 18,
       height = 11,
       scale = 1.1,
       dpi = 320)

fig6


