# Generate tables and figures for Scientific day 2021


# Setup ----------------------------------------------------

# Si c'est sur mon ordi, modifier la locale pour avoir les noms
# des mois en Anglais

if (Sys.info()["login"] == "M-MOUSSET") {
  
  # if (!exists('path.root')) {
  #   source(here::here('R', 'setup.r'), encoding = 'UTF-8')
  # }
  
  # Set locale (so that months appear in english and not French)
  if (Sys.getlocale(category = "LC_TIME") == "French_France.1252") {
    Sys.setlocale(category = "LC_TIME", locale = "C")
    Sys.setenv(LANG = "en_GB.UTF-8") 
  }
  
  # # Upload helper functions
  # source(file.path(path.R, 'utils_management.R'), encoding = 'UTF-8')
  # source(file.path(path.R, 'utils_get_data.R')  , encoding = 'UTF-8')
  # source(file.path(path.R, 'utils_vis.R')       , encoding = 'UTF-8')
  # 
  
  # Set the left and right censoring for date of consultation.
  # The right-censoring create also the week value and the folders where to save outputs
  # dates_and_week <- set_date_frame(create_folders = TRUE)
  # 
  # date_min_report <- dates_and_week[[1]]
  # date_min_report <- as.Date("2020-01-22")
  # date_max_report <- dates_and_week[[2]]
  # week_report     <- dates_and_week[[3]]
  
  
  ## Data
  
  # Geo and population data
  # df_countries <- readRDS(file.path(path.local.data, 'df_countries.RDS'))
  # 
  # # Linelist data 
  # # I'll import the data generated by the episitrep_msf_level_analysyses 
  # # (run episitrep_msf_level first)
  # load(file.path(path.local.msf.data, 
  #                glue::glue('episitrep_msf_level_analyses_{week_report}.RData')))
  
} 

# Définir la semaine
week_report <- "2021-w22"


# Define output folder:
path_sharepoint_js <- "D:/MSF/GRP-EPI-COVID-19 - NCoVEpi/template/scientific-day_2021/figs"
# If week folder not created already, create it.
if (!dir.exists(path_sharepoint_js)) {
  dir.create(path_sharepoint_js, showWarnings = FALSE, recursive = TRUE)
}


# Chemin accès données propres sharepoint (modifier le premier 
# chemin si besoin)
path_sharepoint_sitrep <- "D:/MSF/GRP-EPI-COVID-19 - NCoVEpi/template/sitreps"
path_sharepoint_msf_data <- file.path(path_sharepoint_sitrep, week_report, "msf", "data")
path_sharepoint_jhu_data <- file.path(path_sharepoint_sitrep, week_report, "worldwide", "data")


# Get linelist data (from Sharepoint)
load(file.path(path_sharepoint_msf_data, 
               paste0("episitrep_msf_level_analyses_", week_report, ".RData")))

# Get JHU data (from Sharepoint)
dta_jhu <- readRDS(file.path(path_sharepoint_jhu_data, 'dta_jhu.RDS'))



## Packages ------------------------------------------------
# If they are not on your computer, install the following packages:

library(tidyverse) # General data manipulation
library(lubridate) # To better deal with dates
library(ggplot2)   # Figures
library(scales)    # Improve scales in ggplot
# library(patchwork) # Assemble figures (a bit like cowplot/gridextra)
library(ggthemes)  # For some colours



# Prepare data ----------------------------------------

# Essentially, retain only Confirmed, probable and suspects, 
# define regions to our taste, and turn a couple of stuff in factors
# to preserve order of level.


# Data for analysis: only the confirmed, probable and suspects
dta_linelist_regions <- dta_linelist %>%
  
  # Keep only confirmed, probable and suspected 
  filter(ind_MSF_covid_status %in% c('Confirmed', 'Probable', 'Suspected')) %>%
  
  # Create new columns / clean up columns
  mutate(MSF_severity = ifelse(is.na(MSF_severity), 
                               "Non available", 
                               MSF_severity),
         
         # turn into factor to order
         MSF_severity = factor(MSF_severity,
                               levels = c("Mild", "Moderate", "Severe", 
                                          "Critical", "Non available")),
         # Improve sex
         Sex = factor(patinfo_sex,
                      levels = c('M', 'F'),
                      labels = c('Male', 'Female')),
         
         # Define regions as we want
         region_js = case_when(
           continent == "Europe"        ~ "Europe",
           continent == "Africa"        ~ "Africa",
           continent == "Americas"      ~ "Americas",
           region    == "Western Asia"  ~ "Middle East",
           region    == "Central Asia"  ~ "Asia",
           region    == "Southern Asia" ~ "Asia",
           TRUE ~ region),
         
         region_js = factor(region_js, levels = c("Africa", "Americas",
                                                  "Asia", "Europe", 
                                                  "Middle East")),
         
         delay_before_consultation = as.numeric(MSF_date_consultation - patcourse_dateonset)
  ) 


# The same, but for aggregated data
dta_linelist_regions_aggregated <- dta_linelist_with_aggregated %>%
  filter(ind_MSF_covid_status %in% c('Confirmed', 'Probable', 'Suspected')) %>%
  mutate(region_js = case_when(
    continent == "Europe"        ~ "Europe",
    continent == "Africa"        ~ "Africa",
    continent == "Americas"      ~ "Americas",
    region    == "Western Asia"  ~ "Middle East",
    region    == "Central Asia"  ~ "Asia",
    region    == "Southern Asia" ~ "Asia",
    TRUE ~ region),
    
    region_js = factor(region_js, levels = c("Africa", "Americas",
                                             "Asia", "Europe", 
                                             "Middle East"))
  ) 


# Similar for JHU data (but no probable/conf/suspect à filtrer)
dta_jhu_region <- dta_jhu %>% 
  mutate(
    # Get week number and week start
    epi_week        = lubridate::isoweek(date),
    epi_week_start  = floor_date(date, unit = "week"),
    year            = lubridate::year(date),
    
    region_js = case_when(
      continent == "Europe"        ~ "Europe",
      continent == "Africa"        ~ "Africa",
      continent == "Americas"      ~ "Americas",
      continent == "Oceania"       ~ "Oceania",
      region    == "Western Asia"  ~ "Middle East",
      continent == "Asia" & 
      region !=  "Western Asia"  ~ "Asia",
      TRUE ~ region),
    
    region_js = factor(region_js, levels = c("Africa", "Americas",
                                             "Asia", "Europe", 
                                             "Middle East", "Oceania"))
  )


## Parameters for graphs -----------------------------

# Define a couple of vectors we will need later in graphs

colors_continent <- c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "#000000")
colors_sex <- c("#345B8C", "#8A331F")


vect_labels <- c("Diabetes", "Hypertension", "Renal chronic illness",
                 "Lung disease")
names(vect_labels) <- c("diabetes", "hypertension", "chronic_renal",
                        "lung")


vect_labels2 <- c("Diabetes", "Hypertension", "Renal chronic illness",
                  "Lung disease")
names(vect_labels2) <- c("ind_Comcond_diabetes", 
                         "ind_MSF_hypertension", "Comcond_renal",
                         "Comcond_lung")



# SEX RATIO -------------------------------------------

# Table for numbers in the text

# By region
dta_linelist_regions %>% 
  drop_na(patinfo_sex) %>% 
  group_by(region_js, patinfo_sex) %>% 
  summarise(n_patients = n()) %>% 
  # "Unstack" sex column results
  pivot_wider(names_from = "patinfo_sex",
              values_from = n_patients,
              names_prefix = "count_") %>% 
  # Calculate ratio and proportions
  mutate(ratio_h_f  = round(count_M / count_F, 2),
         prop_h     = round(count_M / (count_M + count_F), 2),
         prop_f     = 1 - prop_h) 

# Globally
dta_linelist_regions %>% 
  drop_na(patinfo_sex) %>% 
  group_by(patinfo_sex) %>% 
  summarise(n_patients = n()) %>% 
  pivot_wider(names_from = "patinfo_sex",
              values_from = n_patients,
              names_prefix = "count_") %>% 
  mutate(ratio_h_f  = round(count_M / count_F, 2))



# ADMISSION  -------------------------------------------

# Noumbers for the text

# Overall
dta_linelist_regions %>%
  filter(merge_admit %in% c("Yes", "No")) %>% 
  group_by(merge_admit) %>% 
  summarise(tot_known = n()) %>% 
  mutate(tot = sum(tot_known),
         perc = round(100 * tot_known / tot, 2))

# Confirmed
dta_linelist_regions %>%
  filter(merge_admit %in% c("Yes", "No"),
         ind_MSF_covid_status == "Confirmed") %>% 
  group_by(merge_admit) %>% 
  summarise(tot_status = n()) %>% 
  mutate(tot = sum(tot_status),
         perc = round(100 * tot_status / tot, 2)) 

# Region
dta_linelist_regions %>%
  filter(merge_admit %in% c("Yes", "No")) %>% 
  group_by(region_js, merge_admit) %>% 
  summarise(tot_status = n()) %>% 
  mutate(tot = sum(tot_status),
         perc = 100 * tot_status / tot) %>% 
  filter(merge_admit  == "Yes")

# By known severity
dta_linelist_regions %>%
  filter(merge_admit == "Yes",
         MSF_severity != "Non available") %>% 
  group_by(MSF_severity) %>% 
  summarise(tot_status = n()) %>% 
  mutate(tot_admitted = sum(tot_status),
         perc = 100 *  tot_status / tot_admitted) 



# CFR -------------------------------------------------

# Overall
dta_linelist_regions %>% 
  filter(ind_outcome_patcourse_status %in% c('Cured', 'Died', 'Sent back home'),
         merge_admit == "Yes") %>% 
  group_by(ind_outcome_patcourse_status) %>% 
  summarise(n_status = n()) %>% 
  mutate(perc = 100 * n_status / sum(n_status)) 

# By region
dta_linelist_regions %>% 
  filter(ind_outcome_patcourse_status %in% c('Cured', 'Died', 'Sent back home'),
         merge_admit == "Yes") %>% 
  group_by(region_js, ind_outcome_patcourse_status) %>% 
  summarise(n_status = n()) %>% 
  mutate(denom = sum(n_status),
         perc = 100 * n_status / sum(n_status)) %>% 
  filter(ind_outcome_patcourse_status == "Died")


# By severity
dta_linelist_regions %>% 
  filter(ind_outcome_patcourse_status %in% c('Cured', 'Died', 'Sent back home'),
         merge_admit == "Yes",
         MSF_severity %in% c("Severe", "Critical")
  ) %>% 
  group_by(MSF_severity, ind_outcome_patcourse_status) %>% 
  summarise(n_status = n()) %>% 
  mutate(denom = sum(n_status),,
         perc = 100 * n_status / sum(n_status)) %>% 
  filter(ind_outcome_patcourse_status == "Died")

# Severe et critique ensemble
dta_linelist_regions %>% 
  filter(ind_outcome_patcourse_status %in% c('Cured', 'Died', 'Sent back home'),
         merge_admit == "Yes",
         MSF_severity %in% c("Severe", "Critical")
  ) %>% 
  group_by(ind_outcome_patcourse_status) %>% 
  summarise(n_status = n()) %>% 
  mutate(denom = sum(n_status),,
         perc = 100 * n_status / sum(n_status)) %>% 
  filter(ind_outcome_patcourse_status == "Died")


# Severe et critique ensemble by region
dta_linelist_regions %>% 
  filter(ind_outcome_patcourse_status %in% c('Cured', 'Died', 'Sent back home'),
         merge_admit == "Yes",
         MSF_severity %in% c("Severe", "Critical")
  ) %>% 
  group_by(region_js, ind_outcome_patcourse_status) %>% 
  summarise(n_status = n()) %>% 
  mutate(denom = sum(n_status),,
         perc = 100 * n_status / sum(n_status)) %>% 
  filter(ind_outcome_patcourse_status == "Died")



# TOTAUX REGIONS ----------------------------------------------

dta_jhu_region %>%
  drop_na(region_js) %>% 
  group_by(region_js) %>% 
  summarise(n_cases = sum(cases,  na.rm = TRUE)) %>% 
  ggplot(aes(x = fct_reorder(region_js, n_cases),
             y = n_cases,
             fill = region_js)) +
  geom_col() +
  coord_flip() +
  geom_text(aes(y     = 91000000,
                label = scales::comma(n_cases)), 
            hjust = 1,
            fontface = "bold",
            size = 4.5
  ) +
  
  scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6),
                     limits = c(0, 100000000),
                     breaks = c(0, 20000000, 40000000, 60000000)
                     # expand = expansion(mult = c(0.02, 0.08))
  ) +
  scale_fill_manual(values = c(colors_continent, "grey60")) +
  labs(x = "",
       y = "") +
  
  theme_light() +
  theme(legend.position = 'none', 
        panel.grid.major.y = element_blank(),
        panel.grid.minor   = element_blank(),
        panel.border       = element_blank(), 
        axis.text.x  = element_text(size = 14, face = "bold"),
        axis.text.y  = element_text(size = 14, face = "bold"),
        axis.title   = element_text(size = 15),
        axis.ticks.y = element_blank()
  )


ggsave(filename = paste0('totaux_region_jhu', '_', week_report, '.png'),
       path = path_sharepoint_js,
       width = 8,
       height = 6,
       dpi = 300)



# EPICURVE WORLD --------------------------------------

# Plot
dta_jhu_region %>%
  drop_na(region_js) %>% 
  group_by(region_js, year, epi_week_start) %>% 
  summarise(n_cases = sum(cases,  na.rm = TRUE)) %>% 
  ggplot(aes(x = epi_week_start, 
             y = n_cases,
             fill = region_js)) +
  geom_col() +
  
  scale_x_date(date_breaks = "2 months",
               labels = scales::label_date_short(),
               expand = expansion(mult = c(0.01, 0.02))) +
  
  scale_y_continuous(labels = scales::unit_format(unit = "M", 
                                                  scale = 1e-6, 
                                                  sep = " "),
                     expand = expansion(mult = c(0.02, 0.04))) +
  scale_fill_manual(values = c(colors_continent, "grey60")) +
  
  labs(x = "",
       y = "Cases") +
  
  theme_light() +
  theme(legend.position  = 'bottom', 
        legend.title     = element_blank(),
        legend.text      = element_text(size = 13),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text   = element_text(size = 15, face = "bold"),
        axis.text.x  = element_text(size = 12),
        axis.text.y  = element_text(size = 14),
        axis.title   = element_text(size = 15))


ggsave(filename = paste0('epicurve_jhu', '_', week_report, '.png'),
       path = path_sharepoint_js,
       width = 10,
       height = 6,
       dpi = 300)


# EPICURVE CAS --------------------------------------------

dta_linelist_regions %>% 
  # Count lines for each subgroup
  count(epi_week_consultation) %>% 
  # Plot
  ggplot(aes(x = epi_week_consultation, 
             y = n)) +
  geom_col(fill = "darkorange3") +
  
  scale_x_date(date_breaks = "2 months",
               labels = scales::label_date_short(),
               # date_labels = "%b %y",
               expand = expansion(mult = c(0.01, 0.02))) +
  scale_y_continuous(name = "Patients", 
                     expand = expansion(mult = c(0, 0.02))) +
  
  labs(x = "\nMonth of consultation / admission",
       y = "Nb patients") +
  
  theme_light() +
  theme(legend.position = 'top', 
        legend.title    = element_text(size = 14, face = "bold"),
        legend.text     = element_text(size = 13),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text   = element_text(size = 15, face = "bold"),
        axis.text.x  = element_text(size = 12),
        axis.text.y  = element_text(size = 14),
        axis.title   = element_text(size = 15))

# Save
ggsave(filename = paste0('epicurve', '_', week_report, '.png'),
       path = path_sharepoint_js,
       width = 10,
       height = 6,
       dpi = 300)



# EPICURVE CAS REGION --------------------------------------------

dta_linelist_regions_aggregated %>% 
  # Count lines for each subgroup
  count(region_js, ind_MSF_covid_status, epi_week_consultation) %>% 
  
  ggplot(aes(x = epi_week_consultation, 
             y = n, 
             fill = ind_MSF_covid_status)) +
  facet_wrap(vars(region_js), scales = 'free_y') +
  geom_col() +
  
  ggthemes::scale_fill_tableau(name = NULL, 
                               palette = "Tableau 20") +
  scale_x_date(date_breaks = "2 months",
               # date_labels = "%b %y",
               labels = scales::label_date_short(),
               expand = expansion(mult = c(0.01, 0.02))) +
  scale_y_continuous(name = "Patients", 
                     expand = expansion(mult = c(0, 0.02))) +
  
  labs(x = "\nMonth of consultation / admission",
       y = "Nb patients") +
  
  theme_light() +
  theme(legend.position = 'top', 
        legend.title    = element_text(size = 14, face = "bold"),
        legend.text     = element_text(size = 13),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text   = element_text(size = 15, face = "bold"),
        axis.text.x  = element_text(size = 12),
        axis.text.y  = element_text(size = 14),
        axis.title   = element_text(size = 15))

# Save
ggsave(filename = paste0('epicurve_region', '_', week_report, '.png'),
       path = path_sharepoint_js,
       width = 14,
       height = 6,
       dpi = 300)


# EPICURVE SEVERITY --------------------------------------------

dta_linelist_regions %>%
  group_by(continent, region_js, epi_week_consultation, MSF_severity) %>%
  summarise(n = n()) %>% 
  drop_na(epi_week_consultation) %>%
  
  ggplot(aes(x = epi_week_consultation,
             y = n,
             fill = MSF_severity)) +
  geom_col() +
  
  # Personalise coulours
  scale_fill_manual(values = palette_Reds4U, 
                    name = "Severity") +
  
  # Personalise x axis
  scale_x_date(date_breaks = "1 month",
               # date_labels = "%b %y",
               labels = scales::label_date_short(),
               expand = expansion(mult = c(0.01, 0.01))) +
  
  labs(x     = "\nMonth of consultation / admission",
       y     = "Nb patients\n",
       title = "Severity - All patients S+P+C") +
  
  theme(legend.title     = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 13),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text   = element_text(size = 15, face = "bold"),
        axis.text.x  = element_text(size = 12),
        axis.text.y  = element_text(size = 14),
        axis.title   = element_text(size = 15))



ggsave(filename = paste0('epicurve_severity', '_', week_report, '.png'),
       path   = path_sharepoint_js,
       width  = 12,
       height = 6,
       dpi    = 320)


# EPICURVE SEVERITY HOSPITALISED --------------------------------------------

## Data ----------------------------------------------------
# Let's get percentage of hospitalisation
dta_hospi <- dta_linelist_regions %>%
  filter(merge_admit %in% c("Yes", "No")) %>% 
  group_by(epi_week_consultation, merge_admit) %>% 
  summarise(n_day = n()) %>% 
  summarise(tot_known      = sum(n_day, na.rm = TRUE),
            n_admitted     = sum(n_day[merge_admit == "Yes"], na.rm = TRUE),
            perc_admitted  = n_admitted / tot_known)

# Let's get data severity
dta_severity_hospi <- dta_linelist_regions %>%
  drop_na(epi_week_consultation) %>%
  filter(merge_admit == "Yes") %>% 
  group_by(epi_week_consultation, MSF_severity) %>%
  summarise(n = n())

# Get scaling factor (for the right axis). I wish it was easier but it's not.
scaling_factor <- dta_severity_hospi %>% 
  group_by(epi_week_consultation) %>% 
  summarise(sum_severity = sum(n)) %>% 
  left_join(dta_hospi %>%  select(epi_week_consultation, perc_admitted), 
            by = "epi_week_consultation") %>%
  summarise(p_admit = max(perc_admitted, na.rm = TRUE),
            n_severity = max(sum_severity, na.rm = TRUE)) %>% 
  mutate(scaling_factor = (p_admit + 0.01) / (n_severity + 0.01)) %>% pull(scaling_factor)


## Plot --------------------------------------
ggplot(dta_severity_hospi,
       aes(x = epi_week_consultation)) +
  geom_col(aes(y = n,
               fill = MSF_severity)) +
  
  # Add the point and line with hospitalised percentage using 
  # the other dataframe
  geom_point(data = dta_hospi,
             aes(y = perc_admitted / scaling_factor)) +
  geom_line(data = dta_hospi,
            aes(y = perc_admitted / scaling_factor)) +
  
  scale_y_continuous(sec.axis = ggplot2::sec_axis(~ . * scaling_factor, 
                                                  name = "Hospitalisation rate", 
                                                  labels = scales::percent_format(accuracy = 2L)),
                     expand = expansion(mult = c(0, 0.02))) +
  
  
  # Personalise coulours
  scale_fill_manual(values = palette_Reds4U, 
                    name = "Severity") +
  
  # Personalise x axis
  scale_x_date(date_breaks = "1 month",
               labels = scales::label_date_short(),
               # date_labels = "%b %y",
               expand = expansion(mult = c(0.01, 0.01))) +
  
  labs(x     = "\nMonth of consultation / admission",
       y     = "Nb patients\n",
       title = "Severity - All HOSPITAZLISED patients S+P+C") +
  
  theme(legend.title     = element_text(size = 14, face = "bold"),
        legend.text      = element_text(size = 13),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text   = element_text(size = 15, face = "bold"),
        axis.text.x  = element_text(size = 12),
        axis.text.y  = element_text(size = 14),
        axis.title   = element_text(size = 15))



ggsave(filename = paste0('epicurve_severity_hospitalised', '_', week_report, '.png'),
       path   = path_sharepoint_js,
       width  = 14,
       height = 6,
       dpi    = 320)




# AGE -----------------------------------------

median(dta_linelist_regions$age_in_years, na.rm = TRUE)

dta_linelist_regions %>% 
  filter(ind_MSF_covid_status == "Confirmed") %>% 
  summarise(med = median(age_in_years, na.rm = TRUE))


## Data ------------------------------------------------

dta_age_median_all <- dta_linelist_regions %>%
  # filter(ind_MSF_covid_status %in% c('Confirmed', 'Probable', 'Suspected')) %>%
  group_by(continent, region_js) %>%
  summarise(x = quantile(age_in_years, c(0.25, 0.5, 0.75), na.rm = TRUE),
            q = c(0.25, 0.5, 0.75),
            n = n()) %>%
  pivot_wider(names_from   = q,
              values_from  = x,
              names_prefix = "q_")


## Fig. age per region -------------------------------

dta_age_median_all %>% 
  ggplot(aes(
    x = region_js,
    y = q_0.5,
    colour = region_js)) + 
  
  geom_point(aes(size = n),
             position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = q_0.25,
                    ymax = q_0.75),
                width = 0,
                size = 1,
                position = position_dodge(width = 0.9)) +
  
  labs(x        = "",
       y        = "Age (years)\n",
       title    = "Median age of patients (with IQR)",
       colour   = "Région") +
  
  scale_size_continuous(name = "Visits",
                        breaks = c(10, 100, 1000, 5000, 10000, 20000)) +
  scale_colour_manual(values = colors_continent) +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title    = element_text(size = 16, face = "bold"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title   = element_text(size = 14),
        legend.text  = element_text(size = 14)) 


ggsave(file.path(path_sharepoint_js, 
                 paste0('median_age_regions', '_', week_report, '.png')),
       width = 7,
       height = 5,
       dpi = 250)


## Fig. pyramid -----------------


pyramid_limits <- function(x) {
  c(-max(abs(x)), max(abs(x)))
}

missing_age_sex <- dta_linelist_regions %>% 
  summarise(age = sum(is.na(age_in_years)), 
            sex = sum(is.na(patinfo_sex)))

# All
dta_linelist_regions %>% 
  filter(epi_week_consultation >= "2020-02-25",
         epi_week_consultation <= "2021-05-23") %>% 
  drop_na(patinfo_sex) %>% 
  group_by(patinfo_sex) %>% 
  summarise(n_patients = n(),
            median_age = median(age_in_years, na.rm = TRUE),
            mean_age   = mean(age_in_years, na.rm = TRUE)) %>% 
  mutate(ratio_h_f  = round(n_patients / sum(n_patients), 2))



# by region
dta_linelist_regions %>% 
  drop_na(patinfo_sex) %>% 
  group_by(region_js, patinfo_sex) %>% 
  summarise(n_patients = n(),
            median_age = median(age_in_years, na.rm = TRUE),
            mean_age   = mean(age_in_years, na.rm = TRUE)) %>% 
  mutate(ratio_h_f  = round(n_patients / sum(n_patients), 2))


tbl_pyramid <- dta_linelist_regions %>% 
  drop_na(patinfo_sex, age_in_years) %>% 
  count(region_js, patinfo_sex, age_9gp) %>% 
  mutate(n = if_else(patinfo_sex == "M", -n, n))



ggplot(tbl_pyramid, 
       aes(x = age_9gp, 
           y = n, 
           fill = patinfo_sex)) +
  geom_col() +
  geom_hline(yintercept = 0, 
             colour = "black") +
  
  coord_flip() +
  facet_wrap(~region_js, scales = "free_x") +
  
  scale_fill_manual(name = NULL, 
                    values = colors_sex, 
                    breaks = c("M", "F"), 
                    labels = c("Males", "Females")) +
  scale_y_continuous(label = abs, limits = pyramid_limits) + 
  
  labs(x = "Age Group\n", 
       y = "\nPatients", 
       caption = glue::glue("Missing Data: Age {missing_age_sex$age}, Sex {missing_age_sex$sex}")) +
  
  theme_light() +
  theme(legend.position = "top",
        legend.text  = element_text(size = 14),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title   = element_text(size = 16, face = "bold"))


# Save
ggsave(filename = paste0('pyramid_age_sex_region', '_', week_report, '.png'),
       path = path_sharepoint_js,
       width = 9,
       height = 8,
       dpi = 200)



# PERC. COMORB. REGION ---------------------------------

# Consultations and hospitalisations

## Fig. ALL  -----------------------------------------------

### Data ------------------------------
dta_comorb_all <- dta_linelist_regions %>%
  group_by(continent, region_js) %>%
  summarise(
    n = n(),
    
    n_diabetes = sum(ind_Comcond_diabetes == "Yes", na.rm = TRUE),
    p_diabetes = n_diabetes / n,
    
    n_hypertension  = sum(ind_MSF_hypertension == "Yes", na.rm = TRUE),
    p_hypertension  = n_hypertension / n,
    
    n_chronic_renal = sum(Comcond_renal == "Yes", na.rm = TRUE),
    p_chronic_renal = n_chronic_renal / n,
    
    
    n_lung = sum(Comcond_lung == "Yes", na.rm = TRUE),
    p_lung = n_lung / n
  ) %>% 
  # stack the percentages for comorbidities in the same column
  pivot_longer(cols = c(p_diabetes, p_hypertension, 
                        p_chronic_renal, p_lung),
               names_to = "Comorbidities",
               values_to = "percent_of_patients",
               names_prefix = "p_") %>%
  filter(percent_of_patients > 0) %>% 
  # Add a column to prepare for the combined figure
  mutate(group_patient = "all",
         Comorbidities = as.factor(Comorbidities))



### Plot --------
dta_comorb_all %>% 
  ggplot(aes(x = region_js,
             y = percent_of_patients,
             colour = region_js)) +
  
  facet_wrap(~ Comorbidities, ncol = 1, scales = "free_y",
             labeller = labeller(Comorbidities = vect_labels)) +
  coord_flip() +
  
  geom_point(size = 3,
             alpha = 1) +
  
  scale_colour_manual(values = colors_continent) +
  scale_y_continuous(labels  = scales::percent_format(accuracy = 1)) +
  
  labs(x = "",
       y = "Patients with comorbidity",
       colour = "Région") +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title    = element_text(size = 13,face = "bold"),
        legend.text     = element_text(size = 13),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(colour = "grey80"),
        strip.text   = element_text(colour = "black", 
                                    size = 15, face = "bold"),
        strip.background = element_rect(fill = "grey90",
                                        colour = "grey80"),
        axis.text.x  = element_text(size = 13),
        axis.text.y  = element_text(size = 13),
        axis.title   = element_text(size = 15))


ggsave(file.path(path_sharepoint_js, 
                 paste0('comorbidities_regions_all', '_', week_report, '.png')),
       width = 7,
       height = 7,
       dpi = 200)


## Fig Severe + Critical ------------------------------------

### Data ------------------------------
dta_comorb_severe_critical <- dta_linelist_regions %>%
  filter(MSF_severity %in% c("Severe", "Critical")) %>% 
  group_by(continent, region_js) %>%
  summarise(
    n = n(),
    
    n_diabetes = sum(ind_Comcond_diabetes == "Yes", na.rm = TRUE),
    p_diabetes = n_diabetes / n,
    
    n_hypertension  = sum(ind_MSF_hypertension == "Yes", na.rm = TRUE),
    p_hypertension  = n_hypertension / n,
    
    n_chronic_renal = sum(Comcond_renal == "Yes", na.rm = TRUE),
    p_chronic_renal = n_chronic_renal / n,
    
    n_lung = sum(Comcond_lung == "Yes", na.rm = TRUE),
    p_lung = n_lung / n
    # n_tb = sum(ind_MSF_tb_active == "Yes", na.rm = TRUE),
    # p_tb = n_tb / n,
    # n_malaria = sum(ind_MSF_malaria == "Yes", na.rm = TRUE),
    # p_malaria = n_malaria / n_hospi,
    # n_hiv = sum(ind_MSF_hiv_status == "Yes", na.rm = TRUE),
    # p_hiv = n_hiv / n_hospi
  ) %>% 
  pivot_longer(cols = c(p_diabetes, p_hypertension, 
                        p_chronic_renal, p_lung),
               names_to = "Comorbidities",
               values_to = "percent_of_patients",
               names_prefix = "p_") %>%
  filter(percent_of_patients > 0) %>% 
  mutate(group_patient = "severe_critical",
         Comorbidities = as.factor(Comorbidities))

dta_comorb_severe_critical_combined <- rbind(dta_comorb_all, dta_comorb_severe_critical)


### Plot ---------
dta_comorb_severe_critical %>% 
  ggplot(aes(x = region_js,
             y = percent_of_patients,
             colour = region_js)) +
  facet_wrap(~ Comorbidities, ncol = 1, scales = "free_y",
             labeller = labeller(Comorbidities = vect_labels)) +
  coord_flip() +
  
  geom_point(size = 3,
             alpha = 1) +
  
  scale_colour_manual(values = colors_continent) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  
  labs(x = "",
       y = "Patients with comorbidity",
       colour = "Region") +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title = element_text(face = "bold"),
        legend.text  = element_text(size = 12),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(colour = "grey80"),
        strip.text   = element_text(colour = "black", 
                                    size = 15, face = "bold"),
        strip.background = element_rect(fill = "grey90",
                                        colour = "grey80"),
        axis.text.x  = element_text(size = 10),
        axis.text.y  = element_text(size = 12),
        axis.title   = element_text(size = 14))


ggsave(file.path(path_sharepoint_js, 
                 paste0('comorbidities_regions_severe_critical', '_', week_report, '.png')),
       width = 7,
       height = 7,
       # scale = 1.1,
       dpi = 300)


## Fig Combined --------------------------------------------

### Plot 1 ----------------
dta_comorb_severe_critical_combined %>% 
  filter(group_patient == "all") %>% 
  
  ggplot(aes(x = region_js,
             y = percent_of_patients,
             colour = region_js,
             alpha  = group_patient,
             size   = group_patient,
             group  = region_js)) +
  facet_wrap(~ Comorbidities, ncol = 1, scales = "free_y",
             labeller = labeller(Comorbidities = vect_labels)) +
  coord_flip() +
  
  geom_point() +
  
  scale_colour_manual(values = colors_continent) +  
  scale_y_continuous(limits = c(0, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  scale_alpha_discrete(range = c(0.4, 1)) +
  scale_size_discrete(range = c(2, 4)) +
  
  labs(x = "",
       y = "Patients with comorbidity",
       colour = "Region",
       alpha  = "Patient",
       size   = "Patient") +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title     = element_text(face = "bold"),
        legend.text = element_text(size = 12),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(colour = "grey80"),
        strip.text   = element_text(colour = "black", 
                                    size = 15, face = "bold"),
        strip.background = element_rect(fill = "grey90",
                                        colour = "grey80"),
        axis.text.x  = element_text(size = 10),
        axis.text.y  = element_text(size = 12),
        axis.title   = element_text(size = 14))


ggsave(file.path(path_sharepoint_js, 
                 paste0('comorbidities_regions__severe_critical_combined_1', '_', week_report, '.png')),
       width = 6,
       height = 9,
       dpi = 300)


### Plot 2 -------------------------------------
dta_comorb_severe_critical_combined %>% 
  # filter(group_patient == "all") %>% 
  ggplot(aes(x = region_js,
             y = percent_of_patients,
             colour = region_js,
             alpha = group_patient,
             size  = group_patient,
             group = region_js)) +
  
  facet_wrap(~ Comorbidities, ncol = 1, scales = "free_y",
             labeller = labeller(Comorbidities = vect_labels)) +
  coord_flip() +
  
  geom_point() +
  # geom_line(size = 0.8,
  #           alpha = 0.5) +
  
  scale_colour_manual(values = colors_continent) +
  scale_y_continuous(limits = c(0, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  scale_alpha_discrete(range = c(0.4, 1)) +
  scale_size_discrete(range = c(2, 4)) +
  
  labs(x = "",
       y = "Patients with comorbidity",
       colour = "Region",
       alpha  = "Patient",
       size   = "Patient") +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title     = element_text(face = "bold"),
        legend.text = element_text(size = 12),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(colour = "grey80"),
        strip.text   = element_text(colour = "black", 
                                    size = 15, face = "bold"),
        strip.background = element_rect(fill = "grey90",
                                        colour = "grey80"),
        axis.text.x  = element_text(size = 10),
        axis.text.y  = element_text(size = 12),
        axis.title   = element_text(size = 14))


ggsave(file.path(path_sharepoint_js, 
                 paste0('comorbidities_regions_severe_critical_combined_2', '_', week_report, '.png')),
       width = 6,
       height = 9,
       dpi = 300)


# MORTALITY COMORB ALL ---------------------------

dta_comorb_mortality_all <- dta_linelist_regions %>%
  # Filtre les lignes
  filter(ind_outcome_patcourse_status %in% c('Cured', 'Died', 'Sent back home'),
         merge_admit == "Yes") %>% 
  # Sélectionne les colonnes (pour simplifier un peu)
  select(region_js, ind_outcome_patcourse_status, ind_Comcond_diabetes, 
         ind_MSF_hypertension, Comcond_renal, Comcond_lung) %>% 
  
  # Stack noms comorbidités dans une colonne et leur présence dans une autre
  pivot_longer(cols = c(ind_Comcond_diabetes, ind_MSF_hypertension, Comcond_renal,
                        Comcond_lung),
               names_to = "comorb_type",
               values_to = "comorb_present") %>% 
  drop_na(comorb_type) %>% 
  filter(comorb_present == "Yes") %>% 
  
  # Compte nb patients par comorb X comorb satus X outcome X region
  count(region_js, ind_outcome_patcourse_status, comorb_type, name = "n_yes") %>% 
  group_by(region_js, comorb_type) %>% 
  summarise(n_known = sum(n_yes, na.rm = TRUE),
            n_died  = sum(n_yes[ind_outcome_patcourse_status  == "Died"], na.rm = TRUE),
            p_died  = n_died / n_known) %>% 
  mutate(comorb_type = factor(comorb_type,
                              levels = c("Comcond_renal", "ind_Comcond_diabetes", 
                                         "ind_MSF_hypertension", "Comcond_lung"),
                              labels = c("Renal chronic illness", "Diabetes",
                                         "Hypertension", "Lung disease")))


### Plot --------
dta_comorb_mortality_all %>% 
  ggplot(aes(x = region_js,
             y = p_died,
             colour = region_js)) +
  facet_wrap(~ comorb_type, ncol = 1, scales = "free_y"
  ) +
  coord_flip() +
  
  geom_point(size = 3,
             alpha = 1) +
  
  scale_colour_manual(values = colors_continent) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  
  labs(x = "",
       y = "Deceased",
       colour = "Region") +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title    = element_text(size = 13,face = "bold"),
        legend.text     = element_text(size = 13),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(colour = "grey80"),
        strip.text   = element_text(colour = "black", 
                                    size = 15, face = "bold"),
        strip.background = element_rect(fill = "grey90",
                                        colour = "grey80"),
        axis.text.x  = element_text(size = 13),
        axis.text.y  = element_text(size = 13),
        axis.title   = element_text(size = 15))


ggsave(file.path(path_sharepoint_js, 
                 paste0('comorbidities_regions_mortality_all', '_', week_report, '.png')),
       width = 7,
       height = 7,
       dpi = 200)




# MORTALITY COMORB SEV/CRIT ---------------------------

# Mortality by comorbidity, only for severe and critial patients.

dta_comorb_mortality_severe_critical <- dta_linelist_regions %>%
  # Filtre les lignes
  filter(ind_outcome_patcourse_status %in% c('Cured', 'Died', 'Sent back home'),
         MSF_severity %in% c("Severe", "Critical"),
         merge_admit == "Yes") %>% 
  # Sélectionne les colonnes (pour simplifier un peu)
  select(region_js, ind_outcome_patcourse_status, ind_Comcond_diabetes, 
         ind_MSF_hypertension, Comcond_renal, Comcond_lung) %>% 
  
  # Stack noms comorbidités dans une colonne et leur présence dans une autre
  pivot_longer(cols = c(ind_Comcond_diabetes, ind_MSF_hypertension, Comcond_renal,
                        Comcond_lung),
               names_to = "comorb_type",
               values_to = "comorb_present") %>% 
  drop_na(comorb_type) %>% 
  filter(comorb_present == "Yes") %>% 
  
  # Compte nb patients par comorb X comorb satus X outcome X region
  count(region_js, ind_outcome_patcourse_status, comorb_type, name = "n_yes") %>% 
  group_by(region_js, comorb_type) %>% 
  summarise(n_known = sum(n_yes, na.rm = TRUE),
            n_died  = sum(n_yes[ind_outcome_patcourse_status  == "Died"], na.rm = TRUE),
            p_died  = n_died / n_known) %>% 
  mutate(comorb_type = factor(comorb_type,
                              levels = c("Comcond_renal", "ind_Comcond_diabetes", 
                                         "ind_MSF_hypertension", "Comcond_lung"),
                              labels = c("Renal chronic illness", "Diabetes",
                                         "Hypertension", "Lung disease")))



### Plot --------
dta_comorb_mortality_severe_critical %>% 
  ggplot(aes(x = region_js,
             y = p_died,
             colour = region_js)) +
  facet_wrap(~ comorb_type, ncol = 1, scales = "free_y") +
  coord_flip() +
  
  geom_point(size = 3,
             alpha = 1) +
  
  scale_colour_manual(values = colors_continent) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  
  labs(x = "",
       y = "Deceased",
       colour = "Region") +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title    = element_text(size = 13,face = "bold"),
        legend.text     = element_text(size = 13),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(colour = "grey80"),
        strip.text   = element_text(colour = "black", 
                                    size = 15, face = "bold"),
        strip.background = element_rect(fill = "grey90",
                                        colour = "grey80"),
        axis.text.x  = element_text(size = 13),
        axis.text.y  = element_text(size = 13),
        axis.title   = element_text(size = 15))


ggsave(file.path(path_sharepoint_js, 
                 paste0('comorbidities_regions_mortality_severe_critical', '_', week_report, '.png')),
       width = 7,
       height = 7,
       dpi = 200)


# DELAY ---------------------------------------------------------------

## Data -------------------
dta_delay_consult <- dta_linelist_regions %>% 
  # filter(ind_MSF_covid_status %in% c("Confirmed")) %>% 
  select(region_js, epi_week_consultation, patcourse_dateonset, 
         MSF_date_consultation, ind_MSF_covid_status, patinfo_sex) %>% 
  drop_na(epi_week_consultation, patcourse_dateonset, patinfo_sex) %>% 
  mutate(
    delay_before_consultation = as.numeric(MSF_date_consultation - patcourse_dateonset)) %>% 
  filter(between(delay_before_consultation, left = 0, right = 50)) %>% 
  # filter(delay_before_consultation > 100) %>% 
  # arrange(delay_before_consultation)
  group_by(region_js, patinfo_sex) %>% 
  summarise(n_with_data = n(),
            delay_median = median(delay_before_consultation, na.rm = TRUE),
            delay_mean   = round(mean(delay_before_consultation, na.rm = TRUE), 1) )


## Plot ---------------------------------
dta_delay_consult %>% 
  ggplot(aes(
    x = patinfo_sex,
    y = delay_median,
    colour = region_js,
    group = region_js)) + 
  facet_wrap(~region_js) +
  
  geom_point(aes(size = n_with_data),
             position = position_dodge(width = 0.9)) +
  geom_line() +
  labs(x        = "",
       y        = "Nb days\n",
       title    = "Median delay before consultation",
       colour   = "Région") +
  
  scale_size_continuous(name = "Visits",
                        breaks = c(10, 100, 1000, 5000, 10000, 20000)) +
  scale_colour_manual(values = colors_continent) +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title    = element_text(size = 16, face = "bold"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title   = element_text(size = 14),
        legend.text  = element_text(size = 14)
  ) 


ggsave(file.path(path_sharepoint_js, 
                 paste0('median_delay_regions', '_', week_report, '.png')),
       width = 7,
       height = 5,
       dpi = 250)




# COINFECTIONS ----------------------------------------

## Fig. ALL  -----------------------------------------------

### Data ------------------------------
dta_coinfections_all <- dta_linelist_regions %>%
  group_by(region_js) %>%
  summarise(
    n = n(),
    
    n_tb = sum(ind_MSF_tb_active == "Yes", na.rm = TRUE),
    p_tb = n_tb / n,
    
    n_malaria = sum(ind_MSF_malaria == "Yes", na.rm = TRUE),
    p_malaria = n_malaria / n,
    
    n_hiv = sum(ind_MSF_hiv_status == "Yes", na.rm = TRUE),
    p_hiv = n_hiv / n
  ) %>% 
  # stack the percentages for comorbidities in the same column
  pivot_longer(cols = c(p_tb, p_malaria, p_hiv),
               names_to = "coinfections",
               values_to = "percent_of_patients",
               names_prefix = "p_") %>%
  filter(percent_of_patients > 0) %>% 
  # Add a column to prepare for the combined figure
  mutate(group_patient = "all")


vect_labels_coinf <- c("Tuberculosis", "Malaria", "HIV")
names(vect_labels_coinf) <- c("tb", "malaria", "hiv")


### Plot --------
dta_coinfections_all %>% 
  ggplot(aes(x = region_js,
             y = percent_of_patients,
             colour = region_js)) +
  
  facet_wrap(~ coinfections, ncol = 1, scales = "free_y",
             labeller = labeller(coinfections = vect_labels_coinf)) +
  coord_flip() +
  
  geom_point(size = 3,
             alpha = 1) +
  
  scale_colour_manual(values = colors_continent) +
  scale_y_continuous(labels  = scales::percent_format(accuracy = 1)) +
  
  labs(x = "",
       y = "Percentage of patients",
       colour = "Région") +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title    = element_text(size = 13,face = "bold"),
        legend.text     = element_text(size = 13),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(colour = "grey80"),
        strip.text   = element_text(colour = "black", 
                                    size = 15, face = "bold"),
        strip.background = element_rect(fill = "grey90",
                                        colour = "grey80"),
        axis.text.x  = element_text(size = 13),
        axis.text.y  = element_text(size = 13),
        axis.title   = element_text(size = 15))


ggsave(file.path(path_sharepoint_js, 
                 paste0('coinfections_regions_all', '_', week_report, '.png')),
       width = 7,
       height = 7,
       dpi = 200)


# OLD STUFF ---------------------
## Fig. age confirmed vs all (slopes)-------------------------

# dta_age_spc <- dta_linelist_regions %>%
#   filter(ind_MSF_covid_status %in% c('Confirmed', 'Probable', 'Suspected')) %>%
#   group_by(continent, region_js) %>%
#   summarise(x = quantile(age_in_years, c(0.25, 0.5, 0.75), na.rm = TRUE),
#             q = c(0.25, 0.5, 0.75),
#             n = n()) %>%
#   pivot_wider(names_from   = q,
#               values_from  = x,
#               names_prefix = "q_") %>% 
#   mutate(status_graphe_js  = as.factor("Susp + Prob + Conf"))
# 
# 
# dta_age_conf <- dta_linelist_regions %>%
#   filter(ind_MSF_covid_status == "Confirmed") %>% 
#   group_by(continent, region_js) %>%
#   summarise(x = quantile(age_in_years, c(0.25, 0.5, 0.75), na.rm = TRUE),
#             q = c(0.25, 0.5, 0.75),
#             n = n()) %>%
#   pivot_wider(names_from = q,
#               values_from =x,
#               names_prefix = "q_") %>% 
#   mutate(status_graphe_js = as.factor("Confirmed"))
# 
# dta_age_median <- rbind(dta_age_spc, dta_age_conf)
# 
# Pentes
# pd_age = 0.5
# colors_status = c("#345B8C", "#8A331F")
# 
# 
# ggplot(dta_age_median,
#        aes(
#          x = status_graphe_js,
#          y = q_0.5,
#          colour = status_graphe_js,
#          shape = status_graphe_js,
#          group = region_js
#        )) +
#   facet_wrap(~continent, ncol = 4, scales = "free_x") +
#   
#   geom_line(colour = "grey",
#             # position = position_dodge(width = pd),
#             size = 1) +
#   geom_point(aes(size = n),
#              # position = position_dodge(width = pd)
#   ) +
#   
#   # geom_errorbar(aes(ymin = q_0.25,
#   #                   ymax = q_0.75),
#   #               width = 0,
#   #               size = 0.1,
#   #               alpha = 0.3,
#   #               position = position_dodge(width = pd)) +
#   # 
#   # coord_flip() +
#   
#   labs(x = "",
#        y = "Age (years)\n",
#        title = "Median age of patients (in years)") +
#   
#   scale_colour_manual(name = "Status",
#                       values = colors_status,
#                       breaks = c("Susp + Prob + Conf", "Confirmed"),
#                       labels = c("Suspected, Probable,\n Confirmed", "Confirmed only")
#   ) +
#   
#   scale_shape(name = "Status",
#               breaks = c("Susp + Prob + Conf", "Confirmed"),
#               labels = c("Suspected, Probable,\n Confirmed", "Confirmed only")
#   ) +
#   
#   scale_size_continuous(name = "Visits",
#                         breaks = c(10, 100, 1000, 5000, 10000, 50000)) +
#   ylim(0, max(dta_age_median$q_0.5)) +
#   scale_x_discrete(expand = expansion(mult = c(0.2, 0.2)),
#                    breaks = c("Susp + Prob + Conf", "Confirmed"),
#                    labels = c("All", "Conf.")) +
#   
#   theme_light() +
#   theme(legend.position = 'right',
#         legend.title = element_text(face = "bold"),
#         axis.text.x = element_text(angle = 50, hjust = 1, face = "bold"),
#         panel.grid.major.y = element_blank(),
#         panel.grid.minor.y = element_blank())
# 
# ggsave(file.path(path_sharepoint_js, 
#                  paste0('median_age_slopes', '_', week_report, '.png')),
#        width = 8,
#        height = 4,
#        # scale = 1,
#        dpi = 200)




# dta_comorb_spc <- dta_linelist_regions %>%
#   filter(merge_admit == "Yes") %>%
#   group_by(continent, region_js) %>%
#   summarise(
#     n_hospi = n(),
#     
#     n_diabetes = sum(ind_Comcond_diabetes == "Yes", na.rm = TRUE),
#     p_diabetes = n_diabetes / n_hospi,
#     n_ind_MSF_hypertension  = sum(ind_MSF_hypertension == "Yes", na.rm = TRUE),
#     p_ind_MSF_hypertension  = n_ind_MSF_hypertension / n_hospi,
#     n_chronic_renal = sum(Comcond_renal == "Yes", na.rm = TRUE),
#     p_chronic_renal = n_chronic_renal / n_hospi,
#     n_tb = sum(ind_MSF_tb_active == "Yes", na.rm = TRUE),
#     p_tb = n_tb / n_hospi,
#     n_malaria = sum(ind_MSF_malaria == "Yes", na.rm = TRUE),
#     p_malaria = n_malaria / n_hospi,
#     n_hiv = sum(ind_MSF_hiv_status == "Yes", na.rm = TRUE),
#     p_hiv = n_hiv / n_hospi) %>% 
#   pivot_longer(cols = c(p_diabetes, p_ind_MSF_hypertension, p_chronic_renal,
#                         p_tb, p_malaria, p_hiv),
#                names_to = "Comorbidities",
#                values_to = "percent_of_hospi",
#                names_prefix = "p_") %>%
#   filter(percent_of_hospi > 0) %>% 
#   mutate(status_graphe_js = as.factor("Susp + Prob + Conf"))
# 
# dta_comorb_conf <- dta_linelist_project %>%
#   filter(ind_MSF_covid_status == "Confirmed") %>% 
#   filter(merge_admit == "Yes") %>%
#   group_by(continent, region_js) %>%
#   summarise(
#     n_hospi = n(),
#     n_diabetes = sum(ind_Comcond_diabetes == "Yes", na.rm = TRUE),
#     p_diabetes = n_diabetes / n_hospi,
#     n_ind_MSF_hypertension  = sum(ind_MSF_hypertension == "Yes", na.rm = TRUE),
#     p_ind_MSF_hypertension  = n_ind_MSF_hypertension / n_hospi,
#     n_chronic_renal = sum(Comcond_renal == "Yes", na.rm = TRUE),
#     p_chronic_renal = n_chronic_renal / n_hospi,
#     n_tb = sum(ind_MSF_tb_active == "Yes", na.rm = TRUE),
#     p_tb = n_tb / n_hospi,
#     n_malaria = sum(ind_MSF_malaria == "Yes", na.rm = TRUE),
#     p_malaria = n_malaria / n_hospi,
#     n_hiv = sum(ind_MSF_hiv_status == "Yes", na.rm = TRUE),
#     p_hiv = n_hiv / n_hospi) %>% 
#   pivot_longer(cols = c(p_diabetes, p_ind_MSF_hypertension, p_chronic_renal,
#                         p_tb, p_malaria, p_hiv),
#                names_to = "Comorbidities",
#                values_to = "percent_of_hospi",
#                names_prefix = "p_") %>%
#   filter(percent_of_hospi > 0) %>% 
#   mutate(status_graphe_js = as.factor("Confirmed"))
# 
# dta_comorb <- rbind(dta_comorb_spc, dta_comorb_conf)
# 
# 

## Fig. Comorb by region (slope) -------------

# dta_comorb %>% 
#   mutate(region_js = factor(region_js)) %>%
#   ggplot(aes(
#     x = status_graphe_js,
#     y = percent_of_hospi,
#     colour = status_graphe_js,
#     group = region_js)) +
#   
#   facet_grid(region_js ~ Comorbidities) +
#   
#   geom_line(colour = "grey",
#             # position = position_dodge(width = pd),
#             size = 1) +
#   geom_point(aes(size = n_hospi),
#              # position = position_dodge(width = pd)
#   ) +
#   
#   labs(x = "",
#        y = "Percentage of hospitalised\n",
#        title = "Comorbidities in hospitalised patients") +
#   
#   scale_colour_manual(name = "Status",
#                       values = colors_status,
#                       breaks = c("Susp + Prob + Conf", "Confirmed"),
#                       labels = c("Suspected, Probable,\n Confirmed", "Confirmed only")
#   ) +
#   
#   scale_size_continuous(name = "Visits",
#                         breaks = c(10, 100, 1000, 5000, 10000, 20000)) +
#   
#   scale_x_discrete(expand = expansion(mult = c(0.2, 0.2)),
#                    breaks = c("Susp + Prob + Conf", "Confirmed"),
#                    labels = c("All", "Conf.")) +
#   ylim(0, 0.5) +
#   theme_light() +
#   theme(legend.position = 'right',
#         legend.title = element_text(face = "bold"),
#         axis.text.x = element_text(angle = 50, hjust = 1, face = "bold"),
#         panel.grid.major.y = element_blank(),
#         panel.grid.minor.y = element_blank(),
#         strip.text.y = element_text(angle = 0))
# 
# 
# 
# ggsave(file.path(path_sharepoint_js, 
#                  paste0('comorbidities_slope_region', '_', week_report, '.png')),
#        width = 10,
#        height = 8,
#        # scale = 1.1,
#        dpi = 250)
# 
# 
# 
# 
## Fig. Comorb by continent (slope) -------------
# 
# pd_comorb <- 0.1
# vect_labels <- c("Diabete", "Hypertension", "Renal chronic illness", 
#                  "Tuberculosis", "Malaria", "HIV")
# names(vect_labels) <- c("diabetes", "ind_MSF_hypertension", "chronic_renal", 
#                         "tb", "malaria", "hiv")
# 
# dta_comorb %>% 
#   ggplot(aes(
#     x = status_graphe_js,
#     y = percent_of_hospi,
#     colour = status_graphe_js,
#     group = region_js)) +
#   
#   facet_grid(continent ~ Comorbidities,
#              labeller = labeller(Comorbidities = vect_labels)) +
#   
#   geom_line(colour = "grey",
#             position = position_dodge(width = pd_comorb),
#             size = 1) +
#   geom_point(aes(size = n_hospi),
#              alpha = 0.7,
#              position = position_dodge(width = pd_comorb)
#   ) +
#   
#   labs(x = "",
#        y = "Percentage of hospitalised\n",
#        title = "Comorbidities in hospitalised patients") +
#   
#   scale_colour_manual(name = "Status",
#                       values = colors_status,
#                       breaks = c("Susp + Prob + Conf", "Confirmed"),
#                       labels = c("Suspected, Probable,\n Confirmed", "Confirmed only")
#   ) +
#   
#   scale_size_continuous(name = "Visits",
#                         breaks = c(10, 100, 1000, 5000, 10000, 20000)) +
#   
#   scale_x_discrete(expand = expansion(mult = c(0.2, 0.2)),
#                    breaks = c("Susp + Prob + Conf", "Confirmed"),
#                    labels = c("All", "Conf.")) +
#   
#   scale_y_continuous(expand = expansion(mult = c(0.1, 0.1)),limits = c(0, 0.4)) +
#   theme_light() +
#   theme(legend.position = 'right',
#         legend.title = element_text(face = "bold"),
#         axis.text.x = element_text(angle = 50, hjust = 1, face = "bold"),
#         panel.grid.major.y = element_blank(),
#         panel.grid.minor.y = element_blank(),
#         strip.text.y = element_text(angle = 0))
# 
# 
# ggsave(file.path(path_sharepoint_js, 
#                  paste0('comorbidities_slope_continent', '_', week_report, '.png')),
#        width = 12,
#        height = 6,
#        # scale = 1.1,
#        dpi = 250)
# 
# ## Exploration delay -----------------------------------
# 
# # A couple of plots to explore data about delay between symptom 
# # onset and date of consultation/hospitalisation.
# 
# 
# dta_delay_consult_severity <- dta_linelist_regions %>% 
#   # filter(ind_MSF_covid_status %in% c("Confirmed")) %>% 
#   select(region_js, epi_week_consultation, patcourse_dateonset, 
#          MSF_date_consultation, ind_MSF_covid_status, patinfo_sex,
#          delay_before_consultation, MSF_severity) %>% 
#   drop_na(patinfo_sex) %>% 
#   
#   filter(between(delay_before_consultation, left = 0, right = 50)) %>% 
#   group_by(region_js, MSF_severity) %>% 
#   summarise(n_with_data = n(),
#             delay_median = median(delay_before_consultation, na.rm = TRUE),
#             delay_mean   = round(mean(delay_before_consultation, na.rm = TRUE), 1) )
# 
# ## Fig. delay and severity ---------------------------------
# dta_delay_consult_severity %>% 
#   ggplot(aes(
#     x = MSF_severity,
#     y = delay_median,
#     colour = MSF_severity)) + 
#   facet_wrap(~region_js) +
#   
#   geom_point(aes(size = n_with_data)) +
#   geom_line() +
#   labs(x        = "",
#        y        = "Nb days\n",
#        title    = "Median delay before consultation",
#        colour   = "Severity") +
#   
#   scale_size_continuous(name = "Visits",
#                         breaks = c(10, 100, 1000, 5000, 10000, 20000)) +
#   scale_colour_manual(values = palette_Reds4U, 
#                       name = "Severity") +
#   theme_light() +
#   theme(legend.position = 'right',
#         legend.title    = element_text(size = 16, face = "bold"),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         axis.text.x  = element_text(size = 14),
#         axis.text.y  = element_text(size = 14),
#         axis.title   = element_text(size = 14),
#         legend.text  = element_text(size = 14)) 
# 
# 
# 
# # Severity and sex ------------------------------------
# 
# 
# dta_delay_consult_severity_sex <- dta_linelist_regions %>% 
#   # filter(ind_MSF_covid_status %in% c("Confirmed")) %>% 
#   select(region_js, epi_week_consultation, patcourse_dateonset, 
#          MSF_date_consultation, ind_MSF_covid_status, patinfo_sex,
#          delay_before_consultation, MSF_severity) %>% 
#   drop_na(patinfo_sex) %>% 
#   
#   filter(between(delay_before_consultation, left = 0, right = 50)) %>% 
#   group_by(region_js, patinfo_sex, MSF_severity) %>% 
#   summarise(n_with_data = n(),
#             delay_median = median(delay_before_consultation, na.rm = TRUE),
#             delay_mean   = round(mean(delay_before_consultation, na.rm = TRUE), 1) )
# 
# ## Fig. delay, severity and sex ---------------------------------
# 
# dta_delay_consult_severity_sex %>% 
#   ggplot(aes(
#     x = patinfo_sex,
#     y = delay_median,
#     colour = MSF_severity,
#     group = MSF_severity)) + 
#   facet_wrap(~region_js) +
#   
#   geom_point(aes(size = n_with_data)) +
#   geom_line() +
#   labs(x        = "",
#        y        = "Nb days\n",
#        title    = "Median delay before consultation",
#        colour   = "Severity") +
#   
#   scale_size_continuous(name = "Visits",
#                         breaks = c(10, 100, 1000, 5000, 10000, 20000)) +
#   # Personalise coulours
#   scale_colour_manual(values = palette_Reds4U, 
#                       name = "Severity") +
#   
#   theme_light() +
#   theme(legend.position = 'right',
#         legend.title    = element_text(size = 16, face = "bold"),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         axis.text.x  = element_text(size = 14),
#         axis.text.y  = element_text(size = 14),
#         axis.title   = element_text(size = 14),
#         legend.text  = element_text(size = 14)) 
# 
# 
# # Inverse sex and severity
# dta_delay_consult_severity_sex %>% 
#   ggplot(aes(
#     x = MSF_severity,
#     y = delay_median,
#     colour = patinfo_sex,
#     group = patinfo_sex)) + 
#   facet_wrap(~region_js) +
#   
#   geom_point(aes(size = n_with_data)) +
#   geom_line() +
#   labs(x        = "",
#        y        = "Nb days\n",
#        title    = "Median delay before consultation",
#        colour   = "Severity") +
#   
#   scale_size_continuous(name = "Visits",
#                         breaks = c(10, 100, 1000, 5000, 10000, 20000)) +
#   # Personalise coulours
#   scale_colour_manual(values = c("red", "blue"), 
#                       name = "Sex") +
#   
#   theme_light() +
#   theme(legend.position = 'right',
#         legend.title    = element_text(size = 16, face = "bold"),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         axis.text.x  = element_text(size = 14, angle = 45, hjust = 1),
#         axis.text.y  = element_text(size = 14),
#         axis.title   = element_text(size = 14),
#         legend.text  = element_text(size = 14)) 
# 
# 
# 
# 
# # Raw data --------------------------------------------
# 
# 
# dta_linelist_regions %>% 
#   # filter(ind_MSF_covid_status %in% c("Confirmed")) %>% 
#   filter(region_js != "Europe") %>% 
#   select(region_js, epi_week_consultation, patcourse_dateonset, 
#          MSF_date_consultation, ind_MSF_covid_status, patinfo_sex,
#          delay_before_consultation, MSF_severity) %>% 
#   drop_na(patinfo_sex) %>% 
#   
#   filter(between(delay_before_consultation, left = 0, right = 50)) %>% 
#   ggplot(aes(x = MSF_severity,
#              y = delay_before_consultation,
#              colour = MSF_severity)) +
#   # facet_wrap(~ region_js) +
#   facet_grid(region_js ~ MSF_severity, scales = "free_x") +
#   geom_jitter(alpha = 0.2) +
#   geom_boxplot(alpha = 0.4, colour = "black") +
#   scale_colour_manual(values = palette_Reds4U, 
#                       name = "Severity") +
#   stat_summary(fun = mean, 
#                geom = "point", 
#                shape = 20, 
#                size = 3, 
#                color = "blue", 
#                fill = "blue")
# 
# 
# 
# 
# # Sex, sévérité et mortalit ---------------------------
# 
# # C'est chaud à explorer tout ça.
# 
# dta_delay_severity_outcome <- dta_linelist_regions %>% 
#   # filter(ind_MSF_covid_status %in% c("Confirmed")) %>% 
#   filter(ind_outcome_patcourse_status %in% c('Cured', 'Died','Sent back home')) %>% 
#   select(region_js, epi_week_consultation, patcourse_dateonset, 
#          MSF_date_consultation, ind_MSF_covid_status, patinfo_sex,
#          delay_before_consultation, MSF_severity, outcome_patcourse_status) %>% 
#   # drop_na(patinfo_sex) %>% 
#   filter(between(delay_before_consultation, left = 0, right = 50)) %>% 
#   group_by(region_js, MSF_severity, outcome_patcourse_status) %>% 
#   summarise(n_tot = n(),
#             delay_median = median(delay_before_consultation, na.rm = TRUE),
#             delay_mean   = round(mean(delay_before_consultation, na.rm = TRUE), 1) )
# 
# 
# # Plot outcome en fonction delay
# dta_delay_severity_outcome %>% 
#   ggplot(aes(x = outcome_patcourse_status,
#              y = delay_median,
#              colour = MSF_severity,
#              group = MSF_severity)) +
#   facet_wrap(~ region_js) +
#   geom_point() +
#   geom_line()







