# Generate tables and figures for Scientific day 2021


# Setup ----------------------------------------------------

if (Sys.info()["login"] == "M-MOUSSET") {
  
  if (!exists('path.root')) {
    source(here::here('R', 'setup.r'), encoding = 'UTF-8')
  }
  
  # Set locale (so that months appear in english and not French)
  if (Sys.getlocale(category = "LC_TIME") == "French_France.1252") {
    Sys.setlocale(category = "LC_TIME", locale = "C")
    Sys.setenv(LANG = "en_GB.UTF-8") 
  }
  
  # Upload helper functions
  source(file.path(path.R, 'utils_management.R'), encoding = 'UTF-8')
  source(file.path(path.R, 'utils_get_data.R')  , encoding = 'UTF-8')
  source(file.path(path.R, 'utils_vis.R')       , encoding = 'UTF-8')
  
  
  # Set the left and right censoring for date of consultation.
  # The right-censoring create also the week value and the folders where to save outputs
  dates_and_week <- set_date_frame(create_folders = TRUE)
  
  date_min_report <- dates_and_week[[1]]
  date_min_report <- as.Date("2020-01-22")
  date_max_report <- dates_and_week[[2]]
  week_report     <- dates_and_week[[3]]

  
  
  ## Data
  
  # Geo and population data
  df_countries <- readRDS(file.path(path.local.data, 'df_countries.RDS'))
  
  # Linelist data 
  # I'll import the data generated by the episitrep_msf_level_analysyses 
  # (run episitrep_msf_level first)
  load(file.path(path.local.msf.data, 
                 glue::glue('episitrep_msf_level_analyses_{week_report}.RData')))
  
} else {
    
  # Définir la semaine
  week_report <- "2021-w20"
  
  # Chemin accès données propres sharepoint (modifier le premier 
  # chemin si besoin)
  path_sharepoint_sitrep <- "D:/MSF/GRP-EPI-COVID-19 - NCoVEpi/template/sitreps/"
  path_sharepoint_msf_data <- file.path(path_sharepoint_sitrep, week_report, "msf", "data")
  
  
  # get data
  load(file.path(path_sharepoint_msf_data, 
                 paste0("episitrep_msf_level_analyses_", week_report, ".RData")))

  }


## Packages ------------------------------------------------
# Install a couple of packages

library(tidyverse) # General data manipulation
library(ggplot)    # Figures
library(patchwork) # Assemble figures (a bit like cowplot/gridextra)
library(ggthemes)  # For some colours



## Paths output --------------------------------------------

# If week folder not created already, create it.
path_sharepoint_js <- "D:/MSF/GRP-EPI-COVID-19 - NCoVEpi/template/scientific-day_2021/figs"

if (!dir.exists(path_sharepoint_js)) {
  dir.create(path_sharepoint_js, showWarnings = FALSE, recursive = TRUE)
}



# Prepare data ----------------------------------------

# Data for analysis: only the confirmed, probable and suspects
dta_linelist_regions <- dta_linelist %>%
  
  # Keep only confirmed, probable and suspected 
  filter(ind_MSF_covid_status %in% c('Confirmed', 'Probable', 'Suspected')) %>%
  
  # Create new columns / clean up columns
  mutate(MSF_severity = ifelse(is.na(MSF_severity), 
                               "Non available", 
                               MSF_severity),
         
         # turn into factor to order
         MSF_severity = factor(MSF_severity,
                               levels = c("Mild", "Moderate", "Severe", 
                                          "Critical", "Non available")),
         # Improve sex
         Sex = factor(patinfo_sex,
                      levels = c('M', 'F'),
                      labels = c('Male', 'Female')),
         
         # Define regions as we want
         region_js = case_when(
           continent == "Europe"        ~ "Europe",
           continent == "Africa"        ~ "Africa",
           continent == "Americas"      ~ "Americas",
           region    == "Western Asia"  ~ "Middle East",
           region    == "Central Asia"  ~ "Asia",
           region    == "Southern Asia" ~ "Asia",
           TRUE ~ region)
         ) 


# The same, but for aggregated data
dta_linelist_regions_aggregated <- dta_linelist_with_aggregated %>%
  filter(ind_MSF_covid_status %in% c('Confirmed', 'Probable', 'Suspected')) %>%
  mutate(region_js = case_when(
           continent == "Europe"        ~ "Europe",
           continent == "Africa"        ~ "Africa",
           continent == "Americas"      ~ "Americas",
           region    == "Western Asia"  ~ "Middle East",
           region    == "Central Asia"  ~ "Asia",
           region    == "Southern Asia" ~ "Asia",
           TRUE ~ region
         )) 


# Parameters for graphs
colors_continent <- c()
colors_sex = c("#8A331F", "#345B8C")


# EPICURVE CAS --------------------------------------------

# Par continent

dta_linelist_regions_aggregated %>% 
  
  # Count lines for each subgroup
  count(region_js, ind_MSF_covid_status, epi_week_consultation) %>% 
  
  # Plot
  ggplot(aes(x = epi_week_consultation, 
             y = n, 
             fill = ind_MSF_covid_status)) +
  facet_wrap(vars(region_js), scales = 'free_y') +
  geom_col() +
  ggthemes::scale_fill_tableau(name = NULL, 
                               palette = "Tableau 20") +
  
  scale_x_date(date_breaks = "2 months",
               date_labels = "%b %y",
               expand = expansion(mult = c(0.01, 0.02))) +
  
  scale_y_continuous(name = "Patients", 
                     expand = expansion(mult = c(0, 0.02))) +
  
  labs(x = "\nMonth of consultation / admission",
       y = "Nb patients", 
       caption = 'NOTE: free y axis scale among graphics') +
  
  theme_light() +
  theme(legend.position = 'top', 
        # legend.title     = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 13),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text   = element_text(size = 15, face = "bold"),
        axis.text.x  = element_text(size = 12),
        axis.text.y  = element_text(size = 14),
        axis.title   = element_text(size = 15))

# Save
ggsave(filename = paste0('epicurve_region', '_', week_report, '.png'),
       path = path_sharepoint_js,
       width = 14,
       height = 6,
       dpi = 300)


# EPICURVE SEVERITY --------------------------------------------

dta_linelist_regions %>%
  group_by(continent, region_js, epi_week_consultation, MSF_severity) %>%
  summarise(n = n()) %>% 
  drop_na(epi_week_consultation) %>%
  
  ggplot(aes(x = epi_week_consultation,
             y = n,
             fill = MSF_severity)) +
  
  geom_col() +
  
  # Personalise coulours
  scale_fill_manual(values = palette_Reds4U, 
                    name = "Severity") +
  
  # Personalise x axis
  scale_x_date(date_breaks = "1 month",
               date_labels = "%b %y",
               expand = expansion(mult = c(0.01, 0.01))) +
  
  labs(x     = "\nMonth of consultation / admission",
       y     = "Nb patients\n",
       title = "Severity - All patients S+P+C") +
  
  theme(legend.title     = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 13),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text   = element_text(size = 15, face = "bold"),
        axis.text.x  = element_text(size = 12),
        axis.text.y  = element_text(size = 14),
        axis.title   = element_text(size = 15))



ggsave(filename = paste0('epicurve_severity', '_', week_report, '.png'),
       path   = path_sharepoint_js,
       width  = 12,
       height = 6,
       dpi    = 320)


# EPICURVE SEVERITY HOSPITALISED --------------------------------------------

## Data ----------------------------------------------------
# Let's get percentage of hospitalisation
dta_hospi <- dta_linelist_regions %>%
  filter(merge_admit %in% c("Yes", "No")) %>% 
  group_by(epi_week_consultation, merge_admit) %>% 
  summarise(n_day = n()) %>% 
  summarise(tot_known      = sum(n_day, na.rm = TRUE),
            n_admitted     = sum(n_day[merge_admit == "Yes"], na.rm = TRUE),
            perc_admitted  = n_admitted / tot_known)

# Let's get data severity
dta_severity_hospi <- dta_linelist_regions %>%
  drop_na(epi_week_consultation) %>%
  filter(merge_admit == "Yes") %>% 
  group_by(epi_week_consultation, MSF_severity) %>%
  summarise(n = n())

# Get scaling factor
scaling_factor <- dta_severity_hospi %>% 
  group_by(epi_week_consultation) %>% 
  summarise(sum_severity = sum(n)) %>% 
  left_join(dta_hospi %>%  select(epi_week_consultation, perc_admitted), 
            by = "epi_week_consultation") %>%
  summarise(p_admit = max(perc_admitted, na.rm = TRUE),
            n_severity = max(sum_severity, na.rm = TRUE)) %>% 
  mutate(scaling_factor = (p_admit + 0.01) / (n_severity + 0.01)) %>% pull(scaling_factor)


## Plot --------------------------------------
ggplot(dta_severity_hospi,
       aes(x = epi_week_consultation)) +
  
  geom_col(aes(y = n,
               fill = MSF_severity)) +
  
  # Add the point and line with hospitalised percentage using 
  # the other dataframe
  geom_point(data = dta_hospi,
             aes(y = perc_admitted / scaling_factor)) +
  geom_line(data = dta_hospi,
            aes(y = perc_admitted / scaling_factor)) +
  
  scale_y_continuous(sec.axis = ggplot2::sec_axis(~ . * scaling_factor, 
                                                  name = "Hospitalisation rate", 
                                                  labels = scales::percent_format(accuracy = 2L)),
                     expand = expansion(mult = c(0, 0.02))) +
  
  
  # Personalise coulours
  scale_fill_manual(values = palette_Reds4U, 
                    name = "Severity") +
  
  # Personalise x axis
  scale_x_date(date_breaks = "1 month",
               date_labels = "%b %y",
               expand = expansion(mult = c(0.01, 0.01))) +
  
  labs(x     = "\nMonth of consultation / admission",
       y     = "Nb patients\n",
       title = "Severity - All HOSPITAZLISED patients S+P+C") +
  
  theme(legend.title     = element_text(size = 14, face = "bold"),
        legend.text      = element_text(size = 13),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text   = element_text(size = 15, face = "bold"),
        axis.text.x  = element_text(size = 12),
        axis.text.y  = element_text(size = 14),
        axis.title   = element_text(size = 15))



ggsave(filename = paste0('epicurve_severity_hospitalised', '_', week_report, '.png'),
       path   = path_sharepoint_js,
       width  = 12,
       height = 6,
       dpi    = 320)






# AGE -----------------------------------------

## Data ------------------------------------------------

dta_age_median_all <- dta_linelist_regions %>%
  # filter(ind_MSF_covid_status %in% c('Confirmed', 'Probable', 'Suspected')) %>%
  group_by(continent, region_js) %>%
  summarise(x = quantile(age_in_years, c(0.25, 0.5, 0.75), na.rm = TRUE),
            q = c(0.25, 0.5, 0.75),
            n = n()) %>%
  pivot_wider(names_from   = q,
              values_from  = x,
              names_prefix = "q_")


## Fig. age per region -------------------------------

dta_age_median_all %>% 
  ggplot(aes(
    x = region_js,
    y = q_0.5 )) + 
  
  geom_point(aes(size = n),
             position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = q_0.25,
                    ymax = q_0.75),
                width = 0,
                position = position_dodge(width = 0.9)) +
  
  labs(x        = "",
       y        = "Age (years)\n",
       title    = "Median age of patients (with IQR)") +
  
  scale_size_continuous(name = "Visits",
                        breaks = c(10, 100, 1000, 5000, 10000, 20000)) +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title    = element_text(size = 16, face = "bold"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x  = element_text(size = 14),
        axis.text.y  = element_text(size = 14),
        axis.title   = element_text(size = 14),
        legend.text  = element_text(size = 14)) 


ggsave(file.path(path_sharepoint_js, 
                 paste0('median_age_regions', '_', week_report, '.png')),
       width = 7,
       height = 5,
       dpi = 250)



# PERC. COMORB. REGION ---------------------------------

# Consultations and hospitalisations
## Fig. ALL  -----------------------------------------------

### Data ------------------------------
dta_comorb_all <- dta_linelist_regions %>%
  group_by(continent, region_js) %>%
  summarise(
    n = n(),
    
    n_diabetes = sum(ind_Comcond_diabetes == "Yes", na.rm = TRUE),
    p_diabetes = n_diabetes / n,
    
    n_ind_MSF_hypertension  = sum(ind_MSF_hypertension == "Yes", na.rm = TRUE),
    p_ind_MSF_hypertension  = n_ind_MSF_hypertension / n,
    
    n_chronic_renal = sum(Comcond_renal == "Yes", na.rm = TRUE),
    p_chronic_renal = n_chronic_renal / n,
    
    n_tb = sum(ind_MSF_tb_active == "Yes", na.rm = TRUE),
    p_tb = n_tb / n,
    
    n_lung = sum(Comcond_lung == "Yes", na.rm = TRUE),
    p_lung = n_lung / n
    # n_malaria = sum(ind_MSF_malaria == "Yes", na.rm = TRUE),
    # p_malaria = n_malaria / n_hospi,
    # n_hiv = sum(ind_MSF_hiv_status == "Yes", na.rm = TRUE),
    # p_hiv = n_hiv / n_hospi
  ) %>% 
  # stack the percentages for comorbidities in the same column
  pivot_longer(cols = c(p_diabetes, p_ind_MSF_hypertension, 
                        p_chronic_renal, p_tb, p_lung),
               names_to = "Comorbidities",
               values_to = "percent_of_patients",
               names_prefix = "p_") %>%
  filter(percent_of_patients > 0) %>% 
  # Add a column to prepare for the combined figure
  mutate(group_patient = "all")


vect_labels <- c("Diabete", "Hypertension", "Renal chronic illness",
                 "Tuberculosis", "Malaria", "HIV", "Lung disease")
names(vect_labels) <- c("diabetes", "ind_MSF_hypertension", "chronic_renal",
                        "tb", "malaria", "hiv", "lung")

### Plot --------
dta_comorb_all %>% 
  ggplot(aes(x = region_js,
             y = percent_of_patients,
             colour = region_js)) +
  geom_point(size = 3,
             alpha = 1) +
  coord_flip() +
  
  facet_wrap(~ Comorbidities, ncol = 1, scales = "free_y",
             labeller = labeller(Comorbidities = vect_labels)) +
  
  ggthemes::scale_colour_tableau(name = "Region",
                                 palette = "Tableau 20") +
  
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  
  labs(x = "",
       y = "Percentage of patients") +

  theme_light() +
  theme(legend.position = 'right',
        legend.title    = element_text(size = 13,face = "bold"),
        legend.text     = element_text(size = 13),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        strip.text   = element_text(size = 15, face = "bold"),
        # strip.background = element_rect(fill = "white"),
        axis.text.x  = element_text(size = 13),
        axis.text.y  = element_text(size = 13),
        axis.title   = element_text(size = 15))


ggsave(file.path(path_sharepoint_js, 
                 paste0('comorbidities_regions_all', '_', week_report, '.png')),
       width = 7,
       height = 7,
       dpi = 200)


## Fig Severe + Critical ------------------------------------

### Data ------------------------------
dta_comorb_severe_critical <- dta_linelist_regions %>%
  filter(MSF_severity %in% c("Severe", "Critical")) %>% 
  group_by(continent, region_js) %>%
  summarise(
    n = n(),
    
    n_diabetes = sum(ind_Comcond_diabetes == "Yes", na.rm = TRUE),
    p_diabetes = n_diabetes / n,
    
    n_ind_MSF_hypertension  = sum(ind_MSF_hypertension == "Yes", na.rm = TRUE),
    p_ind_MSF_hypertension  = n_ind_MSF_hypertension / n,
    
    n_chronic_renal = sum(Comcond_renal == "Yes", na.rm = TRUE),
    p_chronic_renal = n_chronic_renal / n,
    
    n_tb = sum(ind_MSF_tb_active == "Yes", na.rm = TRUE),
    p_tb = n_tb / n,
    
    n_lung = sum(Comcond_lung == "Yes", na.rm = TRUE),
    p_lung = n_lung / n
    # n_malaria = sum(ind_MSF_malaria == "Yes", na.rm = TRUE),
    # p_malaria = n_malaria / n_hospi,
    # n_hiv = sum(ind_MSF_hiv_status == "Yes", na.rm = TRUE),
    # p_hiv = n_hiv / n_hospi
  ) %>% 
  pivot_longer(cols = c(p_diabetes, p_ind_MSF_hypertension, 
                        p_chronic_renal, p_tb, p_lung),
               names_to = "Comorbidities",
               values_to = "percent_of_patients",
               names_prefix = "p_") %>%
  filter(percent_of_patients > 0) %>% 
  mutate(group_patient = "severe_critical")

dta_comorb_combined <- rbind(dta_comorb_all, dta_comorb_severe_critical)

vect_labels <- c("Diabete", "Hypertension", "Renal chronic illness",
                 "Tuberculosis", "Malaria", "HIV", "Lung disease")
names(vect_labels) <- c("diabetes", "ind_MSF_hypertension", "chronic_renal",
                        "tb", "malaria", "hiv", "lung")


### Plot ---------
dta_comorb_severe_critical %>% 
  ggplot(aes(x = region_js,
             y = percent_of_patients,
             colour = region_js)) +
  geom_point(size = 3,
             alpha = 1) +
  coord_flip() +
  
  facet_wrap(~ Comorbidities, ncol = 1, scales = "free_y",
             labeller = labeller(Comorbidities = vect_labels)) +
  
  ggthemes::scale_colour_tableau(name = "Region",
                                 palette = "Tableau 20") +
  
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  
  labs(x = "",
       y = "Percentage of patients") +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title     = element_text(face = "bold"),
        legend.text = element_text(size = 12),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        strip.text   = element_text(size = 14),
        axis.text.x  = element_text(size = 10),
        axis.text.y  = element_text(size = 12),
        axis.title   = element_text(size = 14))


ggsave(file.path(path_sharepoint_js, 
                 paste0('comorbidities_regions_severe_critical', '_', week_report, '.png')),
       width = 7,
       height = 7,
       # scale = 1.1,
       dpi = 300)


## Fig Combined --------------------------------------------

# Plot
dta_comorb_combined %>% 
  filter(group_patient == "all") %>% 
  ggplot(aes(x = region_js,
             y = percent_of_patients,
             colour = region_js,
             alpha = group_patient,
             size  = group_patient,
             group = region_js)) +
  
  facet_wrap(~ Comorbidities, ncol = 1, scales = "free_y",
             labeller = labeller(Comorbidities = vect_labels)) +
  coord_flip() +
  
  geom_point() +
  # geom_line(size = 1,
  #           alpha = 0.9) +
  
  ggthemes::scale_colour_tableau(name = "Region",
                                 palette = "Tableau 20") +
  
  scale_y_continuous(limits = c(0, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  scale_alpha_discrete(range = c(0.4, 1)) +
  scale_size_discrete(range = c(2, 4)) +
  
  
  labs(x = "",
       y = "Percentage of patients") +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title     = element_text(face = "bold"),
        legend.text = element_text(size = 12),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        strip.text   = element_text(size = 14),
        axis.text.x  = element_text(size = 10),
        axis.text.y  = element_text(size = 12),
        axis.title   = element_text(size = 14))


ggsave(file.path(path_sharepoint_js, 
                 paste0('comorbidities_regions_combined_1', '_', week_report, '.png')),
       width = 6,
       height = 9,
       dpi = 300)



#

# Plot
dta_comorb_combined %>% 
  # filter(group_patient == "all") %>% 
  ggplot(aes(x = region_js,
             y = percent_of_patients,
             colour = region_js,
             alpha = group_patient,
             size  = group_patient,
             group = region_js)) +
  
  facet_wrap(~ Comorbidities, ncol = 1, scales = "free_y",
             labeller = labeller(Comorbidities = vect_labels)) +
  coord_flip() +
  
  geom_point() +
  geom_line(size = 0.8,
            alpha = 0.5) +
  
  ggthemes::scale_colour_tableau(name = "Region",
                                 palette = "Tableau 20") +
  
  scale_y_continuous(limits = c(0, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  scale_alpha_discrete(range = c(0.4, 1)) +
  scale_size_discrete(range = c(2, 4)) +
  
  
  labs(x = "",
       y = "Percentage of patients") +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title     = element_text(face = "bold"),
        legend.text = element_text(size = 12),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        strip.text   = element_text(size = 14),
        axis.text.x  = element_text(size = 10),
        axis.text.y  = element_text(size = 12),
        axis.title   = element_text(size = 14))


ggsave(file.path(path_sharepoint_js, 
                 paste0('comorbidities_regions_combined_2', '_', week_report, '.png')),
       width = 6,
       height = 9,
       dpi = 300)


# MORTALITY COMORB SEV/CRIT ---------------------------

# Mortality by comorbidity, only for severe and critial patients.


# OLD STUFF I DONT WANT TO DELETE ---------------------
## Fig. age confirmed vs all (slopes)-------------------------

# dta_age_spc <- dta_linelist_regions %>%
#   filter(ind_MSF_covid_status %in% c('Confirmed', 'Probable', 'Suspected')) %>%
#   group_by(continent, region_js) %>%
#   summarise(x = quantile(age_in_years, c(0.25, 0.5, 0.75), na.rm = TRUE),
#             q = c(0.25, 0.5, 0.75),
#             n = n()) %>%
#   pivot_wider(names_from   = q,
#               values_from  = x,
#               names_prefix = "q_") %>% 
#   mutate(status_graphe_js  = as.factor("Susp + Prob + Conf"))
# 
# 
# dta_age_conf <- dta_linelist_regions %>%
#   filter(ind_MSF_covid_status == "Confirmed") %>% 
#   group_by(continent, region_js) %>%
#   summarise(x = quantile(age_in_years, c(0.25, 0.5, 0.75), na.rm = TRUE),
#             q = c(0.25, 0.5, 0.75),
#             n = n()) %>%
#   pivot_wider(names_from = q,
#               values_from =x,
#               names_prefix = "q_") %>% 
#   mutate(status_graphe_js = as.factor("Confirmed"))
# 
# dta_age_median <- rbind(dta_age_spc, dta_age_conf)
# 
# Pentes
# pd_age = 0.5
# colors_status = c("#345B8C", "#8A331F")
# 
# 
# ggplot(dta_age_median,
#        aes(
#          x = status_graphe_js,
#          y = q_0.5,
#          colour = status_graphe_js,
#          shape = status_graphe_js,
#          group = region_js
#        )) +
#   facet_wrap(~continent, ncol = 4, scales = "free_x") +
#   
#   geom_line(colour = "grey",
#             # position = position_dodge(width = pd),
#             size = 1) +
#   geom_point(aes(size = n),
#              # position = position_dodge(width = pd)
#   ) +
#   
#   # geom_errorbar(aes(ymin = q_0.25,
#   #                   ymax = q_0.75),
#   #               width = 0,
#   #               size = 0.1,
#   #               alpha = 0.3,
#   #               position = position_dodge(width = pd)) +
#   # 
#   # coord_flip() +
#   
#   labs(x = "",
#        y = "Age (years)\n",
#        title = "Median age of patients (in years)") +
#   
#   scale_colour_manual(name = "Status",
#                       values = colors_status,
#                       breaks = c("Susp + Prob + Conf", "Confirmed"),
#                       labels = c("Suspected, Probable,\n Confirmed", "Confirmed only")
#   ) +
#   
#   scale_shape(name = "Status",
#               breaks = c("Susp + Prob + Conf", "Confirmed"),
#               labels = c("Suspected, Probable,\n Confirmed", "Confirmed only")
#   ) +
#   
#   scale_size_continuous(name = "Visits",
#                         breaks = c(10, 100, 1000, 5000, 10000, 50000)) +
#   ylim(0, max(dta_age_median$q_0.5)) +
#   scale_x_discrete(expand = expansion(mult = c(0.2, 0.2)),
#                    breaks = c("Susp + Prob + Conf", "Confirmed"),
#                    labels = c("All", "Conf.")) +
#   
#   theme_light() +
#   theme(legend.position = 'right',
#         legend.title = element_text(face = "bold"),
#         axis.text.x = element_text(angle = 50, hjust = 1, face = "bold"),
#         panel.grid.major.y = element_blank(),
#         panel.grid.minor.y = element_blank())
# 
# ggsave(file.path(path_sharepoint_js, 
#                  paste0('median_age_slopes', '_', week_report, '.png')),
#        width = 8,
#        height = 4,
#        # scale = 1,
#        dpi = 200)




# dta_comorb_spc <- dta_linelist_regions %>%
#   filter(merge_admit == "Yes") %>%
#   group_by(continent, region_js) %>%
#   summarise(
#     n_hospi = n(),
#     
#     n_diabetes = sum(ind_Comcond_diabetes == "Yes", na.rm = TRUE),
#     p_diabetes = n_diabetes / n_hospi,
#     n_ind_MSF_hypertension  = sum(ind_MSF_hypertension == "Yes", na.rm = TRUE),
#     p_ind_MSF_hypertension  = n_ind_MSF_hypertension / n_hospi,
#     n_chronic_renal = sum(Comcond_renal == "Yes", na.rm = TRUE),
#     p_chronic_renal = n_chronic_renal / n_hospi,
#     n_tb = sum(ind_MSF_tb_active == "Yes", na.rm = TRUE),
#     p_tb = n_tb / n_hospi,
#     n_malaria = sum(ind_MSF_malaria == "Yes", na.rm = TRUE),
#     p_malaria = n_malaria / n_hospi,
#     n_hiv = sum(ind_MSF_hiv_status == "Yes", na.rm = TRUE),
#     p_hiv = n_hiv / n_hospi) %>% 
#   pivot_longer(cols = c(p_diabetes, p_ind_MSF_hypertension, p_chronic_renal,
#                         p_tb, p_malaria, p_hiv),
#                names_to = "Comorbidities",
#                values_to = "percent_of_hospi",
#                names_prefix = "p_") %>%
#   filter(percent_of_hospi > 0) %>% 
#   mutate(status_graphe_js = as.factor("Susp + Prob + Conf"))
# 
# dta_comorb_conf <- dta_linelist_project %>%
#   filter(ind_MSF_covid_status == "Confirmed") %>% 
#   filter(merge_admit == "Yes") %>%
#   group_by(continent, region_js) %>%
#   summarise(
#     n_hospi = n(),
#     n_diabetes = sum(ind_Comcond_diabetes == "Yes", na.rm = TRUE),
#     p_diabetes = n_diabetes / n_hospi,
#     n_ind_MSF_hypertension  = sum(ind_MSF_hypertension == "Yes", na.rm = TRUE),
#     p_ind_MSF_hypertension  = n_ind_MSF_hypertension / n_hospi,
#     n_chronic_renal = sum(Comcond_renal == "Yes", na.rm = TRUE),
#     p_chronic_renal = n_chronic_renal / n_hospi,
#     n_tb = sum(ind_MSF_tb_active == "Yes", na.rm = TRUE),
#     p_tb = n_tb / n_hospi,
#     n_malaria = sum(ind_MSF_malaria == "Yes", na.rm = TRUE),
#     p_malaria = n_malaria / n_hospi,
#     n_hiv = sum(ind_MSF_hiv_status == "Yes", na.rm = TRUE),
#     p_hiv = n_hiv / n_hospi) %>% 
#   pivot_longer(cols = c(p_diabetes, p_ind_MSF_hypertension, p_chronic_renal,
#                         p_tb, p_malaria, p_hiv),
#                names_to = "Comorbidities",
#                values_to = "percent_of_hospi",
#                names_prefix = "p_") %>%
#   filter(percent_of_hospi > 0) %>% 
#   mutate(status_graphe_js = as.factor("Confirmed"))
# 
# dta_comorb <- rbind(dta_comorb_spc, dta_comorb_conf)
# 
# 

## Fig. Comorb by region (slope) -------------

# dta_comorb %>% 
#   mutate(region_js = factor(region_js)) %>%
#   ggplot(aes(
#     x = status_graphe_js,
#     y = percent_of_hospi,
#     colour = status_graphe_js,
#     group = region_js)) +
#   
#   facet_grid(region_js ~ Comorbidities) +
#   
#   geom_line(colour = "grey",
#             # position = position_dodge(width = pd),
#             size = 1) +
#   geom_point(aes(size = n_hospi),
#              # position = position_dodge(width = pd)
#   ) +
#   
#   labs(x = "",
#        y = "Percentage of hospitalised\n",
#        title = "Comorbidities in hospitalised patients") +
#   
#   scale_colour_manual(name = "Status",
#                       values = colors_status,
#                       breaks = c("Susp + Prob + Conf", "Confirmed"),
#                       labels = c("Suspected, Probable,\n Confirmed", "Confirmed only")
#   ) +
#   
#   scale_size_continuous(name = "Visits",
#                         breaks = c(10, 100, 1000, 5000, 10000, 20000)) +
#   
#   scale_x_discrete(expand = expansion(mult = c(0.2, 0.2)),
#                    breaks = c("Susp + Prob + Conf", "Confirmed"),
#                    labels = c("All", "Conf.")) +
#   ylim(0, 0.5) +
#   theme_light() +
#   theme(legend.position = 'right',
#         legend.title = element_text(face = "bold"),
#         axis.text.x = element_text(angle = 50, hjust = 1, face = "bold"),
#         panel.grid.major.y = element_blank(),
#         panel.grid.minor.y = element_blank(),
#         strip.text.y = element_text(angle = 0))
# 
# 
# 
# ggsave(file.path(path_sharepoint_js, 
#                  paste0('comorbidities_slope_region', '_', week_report, '.png')),
#        width = 10,
#        height = 8,
#        # scale = 1.1,
#        dpi = 250)
# 
# 
# 
# 
## Fig. Comorb by continent (slope) -------------
# 
# pd_comorb <- 0.1
# vect_labels <- c("Diabete", "Hypertension", "Renal chronic illness", 
#                  "Tuberculosis", "Malaria", "HIV")
# names(vect_labels) <- c("diabetes", "ind_MSF_hypertension", "chronic_renal", 
#                         "tb", "malaria", "hiv")
# 
# dta_comorb %>% 
#   ggplot(aes(
#     x = status_graphe_js,
#     y = percent_of_hospi,
#     colour = status_graphe_js,
#     group = region_js)) +
#   
#   facet_grid(continent ~ Comorbidities,
#              labeller = labeller(Comorbidities = vect_labels)) +
#   
#   geom_line(colour = "grey",
#             position = position_dodge(width = pd_comorb),
#             size = 1) +
#   geom_point(aes(size = n_hospi),
#              alpha = 0.7,
#              position = position_dodge(width = pd_comorb)
#   ) +
#   
#   labs(x = "",
#        y = "Percentage of hospitalised\n",
#        title = "Comorbidities in hospitalised patients") +
#   
#   scale_colour_manual(name = "Status",
#                       values = colors_status,
#                       breaks = c("Susp + Prob + Conf", "Confirmed"),
#                       labels = c("Suspected, Probable,\n Confirmed", "Confirmed only")
#   ) +
#   
#   scale_size_continuous(name = "Visits",
#                         breaks = c(10, 100, 1000, 5000, 10000, 20000)) +
#   
#   scale_x_discrete(expand = expansion(mult = c(0.2, 0.2)),
#                    breaks = c("Susp + Prob + Conf", "Confirmed"),
#                    labels = c("All", "Conf.")) +
#   
#   scale_y_continuous(expand = expansion(mult = c(0.1, 0.1)),limits = c(0, 0.4)) +
#   theme_light() +
#   theme(legend.position = 'right',
#         legend.title = element_text(face = "bold"),
#         axis.text.x = element_text(angle = 50, hjust = 1, face = "bold"),
#         panel.grid.major.y = element_blank(),
#         panel.grid.minor.y = element_blank(),
#         strip.text.y = element_text(angle = 0))
# 
# 
# ggsave(file.path(path_sharepoint_js, 
#                  paste0('comorbidities_slope_continent', '_', week_report, '.png')),
#        width = 12,
#        height = 6,
#        # scale = 1.1,
#        dpi = 250)





