################# PER PROJECT INTERSECTION  ################

# Generate tables and figures for projects on intersection data
# Just a run of what was in the OC level script but in intersection,
# to explore and prepare a draft for the JS.
# (hence tables and figures numbers that may appear random)

# Setup -----------------------------------------------
if (!exists('path.root')) {
  source(here::here('R', 'setup.r'), encoding = 'UTF-8')
}

# Set locale (so that months appear in english and not French)
if (Sys.getlocale(category = "LC_TIME") == "French_France.1252") {
  Sys.setlocale(category = "LC_TIME", locale = "C")
  Sys.setenv(LANG = "en_GB.UTF-8") 
}

# Upload helper functions
source(file.path(path.R, 'utils_management.R'), encoding = 'UTF-8')
source(file.path(path.R, 'utils_get_data.R')  , encoding = 'UTF-8')
source(file.path(path.R, 'utils_vis.R')       , encoding = 'UTF-8')


# Set the left and right censoring for date of consultation.
# The right-censoring create also the week value and the folders where to save outputs
dates_and_week <- set_date_frame(create_folders = TRUE)

date_min_report <- dates_and_week[[1]]
date_min_report <- as.Date("2020-01-22")
date_max_report <- dates_and_week[[2]]
week_report     <- dates_and_week[[3]]

# week_report <- "2021-w19"


### SETUP PATHS ###
# If week folder not created already by overall sitrep, create it.
path.local.msf.extra_js <- file.path(path.local.msf, "extra", "js_2021")

if (!dir.exists(path.local.msf.extra_js)) {
  dir.create(path.local.msf.extra_js,   showWarnings = FALSE, recursive = TRUE)
}


# Get data --------------------------------------------


# Geo and population data
df_countries <- readRDS(file.path(path.local.data, 'df_countries.RDS'))

# Linelist data 
# I'll import the data generated by the episitrep_msf_level_analysyses 
# (run episitrep_msf_level first)
load(file.path(path.local.msf.data, 
               glue::glue('episitrep_msf_level_analyses_{week_report}.RData')))



# Prepare data ----------------------------------------

# Data for per project analysis: only the confirmed, probable and suspects
dta_linelist_regions <- dta_linelist %>%
  filter(ind_MSF_covid_status %in% c('Confirmed', 'Probable', 'Suspected')) %>%
  mutate(MSF_severity = ifelse(is.na(MSF_severity), 
                               "Non available", 
                               MSF_severity),
         MSF_severity = factor(MSF_severity,
                               levels = c("Mild", "Moderate", "Severe", 
                                          "Critical", "Non available")),
         country_project = paste(iso_a3, project, sep = "_"),
         Sex = factor(patinfo_sex,
                      levels = c('M', 'F'),
                      labels = c('Male', 'Female')),
         region_js = case_when(
           continent == "Europe" ~ "Europe",
           region == "Caribbean" ~ "Central America",
           region == "Western Asia" ~ "Middle East",
           region == "Central Asia" ~ "Central / Southern Asia",
           region == "Southern Asia" ~ "Central / Southern Asia",
           region == "Northern Africa" ~ "Northern / Eastern Africa",
           region == "Eastern Africa" ~ "Northern / Eastern Africa",
           TRUE ~ region
         )) 




# AGE -----------------------------------------

colors_sex = c("#8A331F", "#345B8C")


## Data ------------------------------------------------

dta_age_median_all <- dta_linelist_regions %>%
  filter(ind_MSF_covid_status %in% c('Confirmed', 'Probable', 'Suspected')) %>%
  group_by(continent, region_js) %>%
  summarise(x = quantile(age_in_years, c(0.25, 0.5, 0.75), na.rm = TRUE),
            q = c(0.25, 0.5, 0.75),
            n = n()) %>%
  pivot_wider(names_from   = q,
              values_from  = x,
              names_prefix = "q_")


dta_age_spc <- dta_linelist_regions %>%
  filter(ind_MSF_covid_status %in% c('Confirmed', 'Probable', 'Suspected')) %>%
  group_by(continent, region_js) %>%
  summarise(x = quantile(age_in_years, c(0.25, 0.5, 0.75), na.rm = TRUE),
            q = c(0.25, 0.5, 0.75),
            n = n()) %>%
  pivot_wider(names_from   = q,
              values_from  = x,
              names_prefix = "q_") %>% 
  mutate(status_graphe_js  = as.factor("Susp + Prob + Conf"))


dta_age_conf <- dta_linelist_regions %>%
  filter(ind_MSF_covid_status == "Confirmed") %>% 
  group_by(continent, region_js) %>%
  summarise(x = quantile(age_in_years, c(0.25, 0.5, 0.75), na.rm = TRUE),
            q = c(0.25, 0.5, 0.75),
            n = n()) %>%
  pivot_wider(names_from = q,
              values_from =x,
              names_prefix = "q_") %>% 
  mutate(status_graphe_js = as.factor("Confirmed"))

dta_age_median <- rbind(dta_age_spc, dta_age_conf)



## Fig. age confirmed vs all (slopes)-------------------------

# Pentes
pd_age = 0.5
colors_status = c("#345B8C", "#8A331F")


ggplot(dta_age_median,
       aes(
         x = status_graphe_js,
         y = q_0.5,
         colour = status_graphe_js,
         shape = status_graphe_js,
         group = region_js
       )) +
  facet_wrap(~continent, ncol = 4, scales = "free_x") +
  
  geom_line(colour = "grey",
            # position = position_dodge(width = pd),
            size = 1) +
  geom_point(aes(size = n),
             # position = position_dodge(width = pd)
  ) +
  
  # geom_errorbar(aes(ymin = q_0.25,
  #                   ymax = q_0.75),
  #               width = 0,
  #               size = 0.1,
  #               alpha = 0.3,
  #               position = position_dodge(width = pd)) +
  # 
  # coord_flip() +
  
  labs(x = "",
       y = "Age (years)\n",
       title = "Median age of patients (in years)") +
  
  scale_colour_manual(name = "Status",
                      values = colors_status,
                      breaks = c("Susp + Prob + Conf", "Confirmed"),
                      labels = c("Suspected, Probable,\n Confirmed", "Confirmed only")
                      ) +
  
  scale_shape(name = "Status",
              breaks = c("Susp + Prob + Conf", "Confirmed"),
              labels = c("Suspected, Probable,\n Confirmed", "Confirmed only")
              ) +
  
  scale_size_continuous(name = "Visits",
                        breaks = c(10, 100, 1000, 5000, 10000, 50000)) +
  ylim(0, max(dta_age_median$q_0.5)) +
  scale_x_discrete(expand = expansion(mult = c(0.2, 0.2)),
                   breaks = c("Susp + Prob + Conf", "Confirmed"),
                   labels = c("All", "Conf.")) +
  
  theme_light() +
  theme(legend.position = 'right',
        legend.title = element_text(face = "bold"),
        axis.text.x = element_text(angle = 50, hjust = 1, face = "bold"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())

ggsave(file.path(path.local.msf.extra_js, 
                 paste0('median_age_slopes', '_', week_report, '.png')),
       width = 8,
       height = 4,
       # scale = 1,
       dpi = 200)


## Fig. age per region -------------------------------

dta_age_median_all %>% 
  ggplot(aes(
    x = fct_reorder(region_js, desc(continent)),
    y = q_0.5 )) + 
  
  facet_wrap(~ continent, ncol = 1, scales = "free_y") +
  coord_flip() +
  
  geom_point(aes(size = n),
             position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = q_0.25,
                    ymax = q_0.75),
                width = 0,
                position = position_dodge(width = 0.9)) +
  
  labs(x        = "",
       y        = "Age (years)",
       title    = "Median age of all patients (in years)",
       subtitle = "Median and interquartile range") +
  
  scale_size_continuous(name = "Visits",
                        breaks = c(10, 100, 1000, 5000, 10000, 20000)) +
  
  theme_light() +
  theme(legend.position = 'top',
        legend.title = element_text(face = "bold"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()) 


ggsave(file.path(path.local.msf.extra_js, 
                 paste0('median_age_regions', '_', week_report, '.png')),
       width = 6,
       height = 10,
       # scale = 1.1,
       dpi = 250)



# COMORBIDITY (Admitted) ---------------------------------

## Data ------------------------------------------------

dta_comorb_all <- dta_linelist_regions %>%
  filter(merge_admit == "Yes") %>%
  group_by(continent, region_js) %>%
  summarise(
    n_hospi = n(),
    
    n_diabetes = sum(ind_Comcond_diabetes == "Yes", na.rm = TRUE),
    p_diabetes = n_diabetes / n_hospi,
    
    n_ind_MSF_hypertension  = sum(ind_MSF_hypertension == "Yes", na.rm = TRUE),
    p_ind_MSF_hypertension  = n_ind_MSF_hypertension / n_hospi,
    
    n_chronic_renal = sum(Comcond_renal == "Yes", na.rm = TRUE),
    p_chronic_renal = n_chronic_renal / n_hospi,
    
    n_tb = sum(ind_MSF_tb_active == "Yes", na.rm = TRUE),
    p_tb = n_tb / n_hospi,
    
    n_malaria = sum(ind_MSF_malaria == "Yes", na.rm = TRUE),
    p_malaria = n_malaria / n_hospi,
    
    n_hiv = sum(ind_MSF_hiv_status == "Yes", na.rm = TRUE),
    p_hiv = n_hiv / n_hospi) %>% 
  pivot_longer(cols = c(p_diabetes, p_ind_MSF_hypertension, p_chronic_renal,
                        p_tb, p_malaria, p_hiv),
               names_to = "Comorbidities",
               values_to = "percent_of_hospi",
               names_prefix = "p_") %>%
  filter(percent_of_hospi > 0) 



dta_comorb_spc <- dta_linelist_regions %>%
  filter(merge_admit == "Yes") %>%
  group_by(continent, region_js) %>%
  summarise(
    n_hospi = n(),
    
    n_diabetes = sum(ind_Comcond_diabetes == "Yes", na.rm = TRUE),
    p_diabetes = n_diabetes / n_hospi,
    n_ind_MSF_hypertension  = sum(ind_MSF_hypertension == "Yes", na.rm = TRUE),
    p_ind_MSF_hypertension  = n_ind_MSF_hypertension / n_hospi,
    n_chronic_renal = sum(Comcond_renal == "Yes", na.rm = TRUE),
    p_chronic_renal = n_chronic_renal / n_hospi,
    n_tb = sum(ind_MSF_tb_active == "Yes", na.rm = TRUE),
    p_tb = n_tb / n_hospi,
    n_malaria = sum(ind_MSF_malaria == "Yes", na.rm = TRUE),
    p_malaria = n_malaria / n_hospi,
    n_hiv = sum(ind_MSF_hiv_status == "Yes", na.rm = TRUE),
    p_hiv = n_hiv / n_hospi) %>% 
  pivot_longer(cols = c(p_diabetes, p_ind_MSF_hypertension, p_chronic_renal,
                        p_tb, p_malaria, p_hiv),
               names_to = "Comorbidities",
               values_to = "percent_of_hospi",
               names_prefix = "p_") %>%
  filter(percent_of_hospi > 0) %>% 
  mutate(status_graphe_js = as.factor("Susp + Prob + Conf"))




dta_comorb_conf <- dta_linelist_project %>%
  filter(ind_MSF_covid_status == "Confirmed") %>% 
  filter(merge_admit == "Yes") %>%
  group_by(continent, region_js) %>%
  summarise(
    n_hospi = n(),
    n_diabetes = sum(ind_Comcond_diabetes == "Yes", na.rm = TRUE),
    p_diabetes = n_diabetes / n_hospi,
    n_ind_MSF_hypertension  = sum(ind_MSF_hypertension == "Yes", na.rm = TRUE),
    p_ind_MSF_hypertension  = n_ind_MSF_hypertension / n_hospi,
    n_chronic_renal = sum(Comcond_renal == "Yes", na.rm = TRUE),
    p_chronic_renal = n_chronic_renal / n_hospi,
    n_tb = sum(ind_MSF_tb_active == "Yes", na.rm = TRUE),
    p_tb = n_tb / n_hospi,
    n_malaria = sum(ind_MSF_malaria == "Yes", na.rm = TRUE),
    p_malaria = n_malaria / n_hospi,
    n_hiv = sum(ind_MSF_hiv_status == "Yes", na.rm = TRUE),
    p_hiv = n_hiv / n_hospi) %>% 
  pivot_longer(cols = c(p_diabetes, p_ind_MSF_hypertension, p_chronic_renal,
                        p_tb, p_malaria, p_hiv),
               names_to = "Comorbidities",
               values_to = "percent_of_hospi",
               names_prefix = "p_") %>%
  filter(percent_of_hospi > 0) %>% 
  mutate(status_graphe_js = as.factor("Confirmed"))

dta_comorb <- rbind(dta_comorb_spc, dta_comorb_conf)



## Fig. Comorb by region ----------

dta_comorb_all %>% 
  ggplot(aes(x = region_js,
             y = percent_of_hospi,
             colour = continent)) +
  geom_point(size = 3,
             alpha = 0.8) +
  coord_flip() +
  facet_wrap(~Comorbidities, ncol = 2, scales = "free_y") +
  
  ggthemes::scale_colour_tableau(name = "Comorbidities",
                                 palette = "Tableau 20") +
  
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  
  theme_light() +
  theme(legend.position = 'right',
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()) +
  
  labs(x = "",
       y = "Percentage of hospitalised patients",
       title = "Mortality and comorbidities")

# breaks = c("diabetes", "ind_MSF_hypertension", "chronic_renal", "tb", "malaria", "hiv"),
# labels = c("Diabete", "Hypertension", 
#            "Renal chronic illness", 
#            "Tuberculosis", "Malaria", "HIV")


ggsave(file.path(path.local.msf.extra_js, 
                 paste0('comorbidities_regions', '_', week_report, '.png')),
       width = 10,
       height = 8,
       # scale = 1.1,
       dpi = 250)



## Fig. Comorb by region (slope) -------------

dta_comorb %>% 
  mutate(region_js = factor(region_js)) %>%
  ggplot(aes(
    x = status_graphe_js,
    y = percent_of_hospi,
    colour = status_graphe_js,
    group = region_js)) +
  
  facet_grid(region_js ~ Comorbidities) +
  
  geom_line(colour = "grey",
            # position = position_dodge(width = pd),
            size = 1) +
  geom_point(aes(size = n_hospi),
             # position = position_dodge(width = pd)
  ) +
  
  labs(x = "",
       y = "Percentage of hospitalised\n",
       title = "Comorbidities in hospitalised patients") +
  
  scale_colour_manual(name = "Status",
                      values = colors_status,
                      breaks = c("Susp + Prob + Conf", "Confirmed"),
                      labels = c("Suspected, Probable,\n Confirmed", "Confirmed only")
  ) +
  
  scale_size_continuous(name = "Visits",
                        breaks = c(10, 100, 1000, 5000, 10000, 20000)) +
  
  scale_x_discrete(expand = expansion(mult = c(0.2, 0.2)),
                   breaks = c("Susp + Prob + Conf", "Confirmed"),
                   labels = c("All", "Conf.")) +
  ylim(0, 0.5) +
  theme_light() +
  theme(legend.position = 'right',
        legend.title = element_text(face = "bold"),
        axis.text.x = element_text(angle = 50, hjust = 1, face = "bold"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        strip.text.y = element_text(angle = 0))



ggsave(file.path(path.local.msf.extra_js, 
                 paste0('comorbidities_slope_region', '_', week_report, '.png')),
       width = 10,
       height = 8,
       # scale = 1.1,
       dpi = 250)




## Fig. Comorb by continent (slope) -------------

pd_comorb <- 0.1
vect_labels <- c("Diabete", "Hypertension", "Renal chronic illness", 
                 "Tuberculosis", "Malaria", "HIV")
names(vect_labels) <- c("diabetes", "ind_MSF_hypertension", "chronic_renal", 
                        "tb", "malaria", "hiv")

dta_comorb %>% 
  ggplot(aes(
    x = status_graphe_js,
    y = percent_of_hospi,
    colour = status_graphe_js,
    group = region_js)) +
  
  facet_grid(continent ~ Comorbidities,
             labeller = labeller(Comorbidities = vect_labels)) +
  
  geom_line(colour = "grey",
            position = position_dodge(width = pd_comorb),
            size = 1) +
  geom_point(aes(size = n_hospi),
             alpha = 0.7,
             position = position_dodge(width = pd_comorb)
  ) +
  
  labs(x = "",
       y = "Percentage of hospitalised\n",
       title = "Comorbidities in hospitalised patients") +
  
  scale_colour_manual(name = "Status",
                      values = colors_status,
                      breaks = c("Susp + Prob + Conf", "Confirmed"),
                      labels = c("Suspected, Probable,\n Confirmed", "Confirmed only")
  ) +
  
  scale_size_continuous(name = "Visits",
                        breaks = c(10, 100, 1000, 5000, 10000, 20000)) +
  
  scale_x_discrete(expand = expansion(mult = c(0.2, 0.2)),
                   breaks = c("Susp + Prob + Conf", "Confirmed"),
                   labels = c("All", "Conf.")) +
  
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.1)),limits = c(0, 0.4)) +
  theme_light() +
  theme(legend.position = 'right',
        legend.title = element_text(face = "bold"),
        axis.text.x = element_text(angle = 50, hjust = 1, face = "bold"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        strip.text.y = element_text(angle = 0))


ggsave(file.path(path.local.msf.extra_js, 
                 paste0('comorbidities_slope_continent', '_', week_report, '.png')),
       width = 12,
       height = 6,
       # scale = 1.1,
       dpi = 250)
